-- v69: especialidade, cidade e estado de cada mentorado.
--
-- A planilha escreve a especialidade de 80 jeitos diferentes ("Nutrologia",
-- "Nutrologo", "Nutróloga", "Nutologia"...). Aqui elas viram 22 nomes
-- padronizados — sem isso nenhum gráfico faz sentido. O texto original fica
-- guardado em `especialidade_original`, pra nada se perder.
--
-- A cidade vem como "Vitória/ES": separo em cidade e estado (UF), que é o
-- que permite agrupar por região.

alter table students add column if not exists especialidade text;
alter table students add column if not exists especialidade_original text;
alter table students add column if not exists cidade text;
alter table students add column if not exists uf text;
alter table students add column if not exists cidade_uf text;

drop table if exists dados_extras;
create table dados_extras (
  email text primary key, especialidade text, cidade text, uf text,
  especialidade_original text, evento_mentalidade text, levara_conjuge text
);
insert into dados_extras (email,especialidade,cidade,uf,especialidade_original,evento_mentalidade,levara_conjuge) values
  ('luanacb@icloud.com','Nutrologia','Maceió','AL','Nutróloga',null,null),
  ('zanella.alice@gmail.com','Cardiologia','Frederico Westphalen','RS','cardiologista',null,null),
  ('anarobertaandrada@hotmail.com','Endocrinologia','Brasilia','DF','Endocrinologista',null,null),
  ('aandressadepaula@gmail.com','Ginecologia','Viçosa/Ponte Nova','MG','Ginecologista',null,null),
  ('augustofavaleite@gmail.com','Psiquiatria','João Monlevade','MG','Psiquiatra',null,null),
  ('biancacdamin@gmail.com','Infectologia','Cuiabá','MT','Infectologista',null,null),
  ('drablimaderossi@hotmail.com','Nutrologia','Vitória','ES','Nutrologia',null,null),
  ('bruhandressa23@icloud.com','Ginecologia','Itanhangá','MT','Ginecologista',null,null),
  ('drabrunahering@gmail.com','Dermatologia','São Paulo','SP','Dermatologia',null,null),
  ('bruno.aguila87@gmail.com','Cirurgia','Mossoró','RN','Cirurgião Oncológico',null,null),
  ('cami_gava@hotmail.com','Emagrecimento e Metabolismo','Curitiba','PR','Emagrecimento',null,null),
  ('ctplacerda@outlook.com','Nutrologia','Leblon','RJ','Nutrologia',null,null),
  ('chrisfalci@hotmail.com','Endocrinologia','Governador Valadares','MG','Endocrinologista',null,null),
  ('cibele-lemos@hotmail.com','Cirurgia','Passos / MG (Cidade Nova/SP)',null,'Cirurgiã',null,null),
  ('dania.albuquerque@gmail.com','Ginecologia','Caruaru','PE','Ginecologista',null,null),
  ('raspini@hotmail.com','Ginecologia','Brusque','SC','Ginecologista',null,null),
  ('eduardojorge@oncoginecologia.com.br','Ginecologia','São Paulo','SP','Ginecologista',null,null),
  ('endetaned@outlook.com','Endocrinologia','São Luis','MA','Endocrinologista',null,null),
  ('fabianamiranda793@gmail.com','Endocrinologia','Indaiabira','MG','Endocrinologista',null,null),
  ('moraesfernandap@gmail.com','Cirurgia','Apiaí','SP','Cirurgiã',null,null),
  ('gisaffonseca@hotmail.com','Ginecologia','Belém','PA','Ginecologista',null,null),
  ('glauco.piassi@hotmail.com','Cardiologia','Passos','MG','cardiologista',null,null),
  ('isabellaccarvalho_@outlook.com','Nutrologia','Ourinnhos','SP','Nutrologia',null,null),
  ('draisabellacunha@gmail.com','Ginecologia','Volta Redonda','RJ','Ginecologista',null,null),
  ('isadora.angelicola@gmail.com','Ginecologia','Ribeirão Preto','SP','Ginecologista',null,null),
  ('joaofon2912@gmail.com','Emagrecimento e Metabolismo','Aracaju','SE','Hormonologia',null,null),
  ('drsouzajrkef@gmail.com','Ginecologia','Rio Verde','GO','Ginecologista',null,null),
  ('karinerantunes@hotmail.com','Endocrinologia','Itajubá','SP','Endocrinologista',null,null),
  ('karolinemcosta@yahoo.com.br','Ginecologia','Belo Horinzonte','MG','Ginecologista',null,null),
  ('layzaandrade_84@hotmail.com','Ginecologia','Mossoró','RN','Ginecologista',null,null),
  ('neto_bz@hotmail.com','Nutrologia','Belo Horinzonte','MG','Clinico Geral/Nutrologia',null,null),
  ('liviaapvasconcelos@gmail.com','Cirurgia','Maceió','AL','Cirurgiã Oncológica',null,null),
  ('lucymaria-bdc@hotmail.com','Nutrologia','Governador Valadares','MG','Nutologia',null,null),
  ('luisacastelob2@hotmail.com','Ginecologia','Salvador','BA','Ginecologista',null,null),
  ('luizfernandocabralrezende@hotmail.com','Medicina de Família','Três Mariaas','MG','Medicina Família',null,null),
  ('marvis.mv@gmail.com','Clínica Geral','Santa Inês','MA','Generalista',null,null),
  ('mbdalcol@hotmail.com','Ginecologia','Ecoporanga','ES','Ginecologista',null,null),
  ('drmateusfacchin@gmail.com','Medicina do Esporte','Caxias do Sul','RS','Medico do esporte',null,null),
  ('micheleferraz87@gmail.com','Endocrinologia','Formosa','GO','Endocrinologista',null,null),
  ('nis_mohammed@hotmail.com','Ginecologia','Corumbá','MS','Ginecologista',null,null),
  ('normanagime@yahoo.com.br','Endocrinologia','Governador Valadares','MG','Endocrinologista',null,null),
  ('vitorianoneto@gmail.com','Endocrinologia','Obidos','PA','Endocrinologista',null,null),
  ('drrenanagarcia@gmail.com','Emagrecimento e Metabolismo','Cabo Frio','RJ','Emagrecimento',null,null),
  ('robertapvm@gmail.com','Dermatologia','Petrópolis','RJ','Dermatologista',null,null),
  ('romolo.guida@gmail.com','Urologia','Rio de Janeiro','RJ','Urologista',null,null),
  ('sfcentermed@gmail.com','Nutrologia','Ilhabela','SP','Nutrologo',null,null),
  ('sohailadalbianco@gmail.com','Medicina do Esporte','Porto Alegre','RS','Medico do esporte',null,null),
  ('suzanasralves@gmail.com','Clínica Geral','Amazonas','AM','Clico Geral',null,null),
  ('dratatianenacif@gmail.com','Ginecologia','Caratinga','MG','Ginecologista',null,null),
  ('thaismnzs@yahoo.com.br','Ginecologia','Belem','PA','Ginecologista',null,null),
  ('drathaisabramusse@gmail.com','Emagrecimento e Metabolismo','Belo Horinzonte','MG','Emagrecimento',null,null),
  ('vanessalbrandao@gmail.com','Ginecologia','Patos de Minas','MG','Ginecologista',null,null),
  ('vanrochapessoa@hotmail.com','Ginecologia','Eusébio','CE','Ginecologista',null,null),
  ('wendel.petrucio@gmail.com','Ginecologia','Manaus','AM','Ginecologista',null,null),
  ('felipe_dipaula.a@hotmail.com','Psiquiatria','Juiz de Fora','MG','Psiquiatra',null,null),
  ('dra.terciasousa.med@gmail.com/tercia_tarciane@hotmail.com','Oncologia','São Paulo','SP','Oncologista',null,null),
  ('mmunizspadini@gmail.com','Dermatologia','São Paulo','SP','Dermatologista',null,null),
  ('aj_motta@hotmail.com','Ginecologia','Catalão','GO','Ginecologista',null,null),
  ('contato@sincrovida.com.br','Nefrologia','Botucatu','SP','Nefrologista',null,null),
  ('dradjeime@gmail.com','Nutrologia','São Paulo','SP','Nutrologo',null,null),
  ('ronaldomorari@gmail.com','Endocrinologia','Macapá','AP','Endocrinologista',null,null),
  ('scheilasilva@yahoo.com.br','Ginecologia','Palmitinho','RS','Ginecologista',null,null),
  ('albinopaim4@outlook.com','Neurologia','Feira de Santana','BA','Neurologista',null,null),
  ('tascila74@gmail.com','Ginecologia','São Jose dos Campos','SP','Ginecologista',null,null),
  ('thaisabreureggiani@gmail.com','Ginecologia','Timóteo','MG','Ginecologista',null,null),
  ('ketlimpriscilla@hotmail.com','Medicina de Família','Alta Floresta do Oeste','RO','Medica de Familia',null,null),
  ('c-juliani@hotmail.com','Ginecologia','Luis Eduardo Magalhães','BA','Ginecologista',null,null),
  ('cantarelli@cmdiagnostica.com.br','Ginecologia','Maceió','AL','Ginecologista',null,null),
  ('esther-amorim@hotmail.com','Ginecologia','Ponte Nova','MG','Ginecologista',null,null),
  ('dr.fredericofchaves@gmail.com','Clínica Geral','São João da Boa Vista','SP','Generalista',null,null),
  ('drakarinakakizaki@gmail.com','Clínica Geral','Sinop','MT','Clico Geral',null,null),
  ('nayaracibelly@gmail.com','Nutrologia','Santa Rosa de Goias','GO','Nutrologo',null,null),
  ('dramarcelabrasil@hotmail.com','Nutrologia','Divinopolis','MG','Nutrologo',null,null),
  ('isarampazzo@me.com','Ginecologia','Maringá','PR','Ginecologista',null,null),
  ('savionobree@hotmail.com','Endoscopia','Guaraciaba do Norte','CE','Endoscopia',null,null),
  ('ramos.almino@gmail.com','Cirurgia Bariátrica','São Paulo','SP','Cirurgião Bariatrico',null,null),
  ('drbrunormota@bol.com.br','Cirurgia Bariátrica','Maceió','AL','Cirurgião Bariatrico',null,null),
  ('cinthiafeijo@hotmail.com','Nutrologia','João Pessoa','PB','Nutrologa',null,null),
  ('claudio.pe91@gmail.com','Cirurgia Bariátrica','Imperatriz','MA','Cirurgião Bariatrico',null,null),
  ('edgof@yahoo.com.br','Anestesiologia','João Pessoa','PB','Anestologista',null,null),
  ('gerlianom@gmail.com','Cirurgia Bariátrica','Cachoeiro do Itapemerim','ES','Cirurgião Bariatrico',null,null),
  ('giorgio.baretta@gmail.com','Clínica Geral','Curitiba','PR','Clinico Geral',null,null),
  ('drgustavocoimbra@gmail.com','Cirurgia','Belo Horizonte','MG','Cirurgião Geral',null,null),
  ('faturamento@gastro-centro.com / jnicareta@uol.com.br//jnicareta@gmail.com','Cirurgia Bariátrica','Guarapuava','PR','Cirurgião Bariatrico',null,null),
  ('drjimi@scarparoscopia.com','Cirurgia Bariátrica','São Paulo','SP','Cirurgião Bariatrico',null,null),
  ('drvaladaoslz@gmail.com','Cirurgia Bariátrica','São Luis','MA','Cirurgião Bariatrico',null,null),
  ('jully.scarparo@gmail.com','Cirurgia Bariátrica','São Paulo','SP','Cirurgião Bariatrico',null,null),
  ('drlucasrossi@gmail.com','Cirurgia Bariátrica','Porto Alegre','RS','Cirurgião Bariatrico',null,null),
  ('lslucianasiqueira@gmail.com','Cirurgia Bariátrica','Recife','PE','Cirurgião Bariatrico',null,null),
  ('galvao.manoela@gmail.com','Cirurgia Bariátrica','São Paulo','SP','Cirurgião Bariatrico',null,null),
  ('marcioschenato@gmail.com','Cirurgia Bariátrica','Francisco Beltrão','PR','Cirurgião Bariatrico',null,null),
  ('mayaramasilva@hotmail.com//dramayaramagry@gmail.com','Cirurgia Bariátrica','Imperatriz','MA','Cirurgião Bariatrico',null,null),
  ('paulovblima@gmail.com','Cirurgia Bariátrica','Maceió','AL','Cirurgião Bariatrico',null,null),
  ('raphael_torres@hotmail.com','Cirurgia Bariátrica','São Paulo','SP','Cirurgião Bariatrico',null,null),
  ('ttsbrasil@gmail.com','Cirurgia Bariátrica','São Paulo','SP','Cirurgião Bariatrico',null,null),
  ('vieira.vitor1@gmail.com','Cirurgia Bariátrica','Curitiba','PR','Cirurgião Bariatrico',null,null),
  ('andreiakataiama@gmail.com','Cirurgia Bariátrica','São Paulo','SP','cirurgião Bariatrico',null,null),
  ('talytasv@gmail.com','Cirurgia Bariátrica','Campina Grande','PB','cirurgião Bariatrico',null,null),
  ('alessandracmiranda@icloud.com','Nutrologia','Goiânia / GO e Uberaba','MG','Nutróloga',null,null),
  ('dramanda.go@hotmail.com','Ginecologia','São Gotardo','MG','Ginecologista e Obstetra',null,null),
  ('amanda_aarao@yahoo.com.br','Nutrologia','Vitória','ES','Cardiologia e Nutrologia',null,null),
  ('aninhaabt@yahoo.com.br',null,null,null,null,null,null),
  ('bumlima@hotmail.com','Ginecologia','Curitiba','PR','Ginecologista',null,null),
  ('camilecardosoo@gmail.com',null,null,null,null,null,null),
  ('carolcassabgenaro@hotmail.com','Cardiologia','Rio Claro','SP','Cardiologista',null,null),
  ('carolfariamiurim@hotmail.com','Ginecologia','Baixo Guandu/ ES e Resplendor','MG','Ginecologista',null,null),
  ('cybertoldo@hotmail.com','Ginecologia','Brasilia','DF','Ginecologista',null,null),
  ('ddenovaisalves@gmail.com','Ginecologia','Salvador','BA','Ginecologista',null,null),
  ('djeniferscheila@hotmail.com',null,null,null,null,null,null),
  ('elisasouzalima@yahoo.com.br','Ginecologia','Vila Velha','ES','Ginecologista',null,null),
  ('emimax_babii@hotmail.com',null,'Rolim de Moura','RO',null,null,null),
  ('fernanda.c.roque@hotmail.com','Ginecologia','Vila Velha','ES','Ginecologista',null,null),
  ('dra_flaviamonteiro@hotmail.com','Oftalmologia','Rio Claro','SP','Oftalmologia',null,null),
  ('gabi_webers@hotmail.com','Ginecologia','Tubarão','SC','Ginecologista',null,null),
  ('gisela_altoe@hotmail.com','Ginecologia','Vargem Alta','ES','Gineco, obstetra e nutróloga',null,null),
  ('driuriromanov@gmail.com','Nutrologia','Colatina','ES','Nutrologia',null,null),
  ('junnybelache@hotmail.com','Nutrologia','Rio de Janeiro','RJ','Nutrologia',null,null),
  ('lara_figueiredo4@hotmail.com','Nutrologia','Mossoró','RN','Nutrologia',null,null),
  ('dra.larissaazevedo@gmail.com','Cirurgia','Aracaju','SE','Cirurgiã Vascular',null,null),
  ('layaneferreirab@gmail.com',null,'Boa Vista','RR',null,null,null),
  ('leticia.b.alvim@gmail.com','Endocrinologia','Boituva','SP','Endocrinologista',null,null),
  ('lizardamed@hotmail.com','Ginecologia','Maceió','AL','Ginecologista',null,null),
  ('luan.tagiaroli.f@gmail.com','Nutrologia','São Paulo','SP','Nutrólogo',null,null),
  ('dra.luanaalegrefelix@gmail.com','Endocrinologia','Ribeirão Preto','SP','Endocrinologista',null,null),
  ('ximenes_luciana@hotmail.com','Ginecologia','Itaperuna','RJ','Gineco e Obstetra',null,null),
  ('marialuisagomes23@hotmail.com','Endocrinologia','Barra de São Francisco','ES','Endocrinologista',null,null),
  ('dramariamviviane@gmail.com','Ginecologia','Brasília','DF','Ginecologista',null,null),
  ('cmateusr@gmail.com',null,null,null,null,null,null),
  ('mahteusferrari@gmail.com','Endocrinologia','Uberlândia','MG','Endocrinologia',null,null),
  ('naiara_fumagalli@yahoo.com.br','Ginecologia','Sorocaba','SP','Ginecologista',null,null),
  ('nadhinecalheiros@outlook.com','Nutrologia','Maceió','AL','Nutrologia',null,null),
  ('osnjunior@hotmail.com','Ginecologia','Colatina','ES','Ginecologista',null,null),
  ('rbmadruga@gmail.com','Ginecologia','Rio de Janeiro','RJ','Gineco e obstetra',null,null),
  ('rodrigoljalves@gmail.com','Endocrinologia','Barueri','SP','Endocrinologia',null,null),
  ('drsandrapersonal@gmail.com','Ginecologia','Paulínia','SP','Ginecologista',null,null),
  ('sszanindra@gmail.com','Endocrinologia','São Paulo','SP','Endocrinologia',null,null),
  ('tamiris.giacomin@gmail.com',null,null,null,null,null,null),
  ('tatianefernandesv@gmail.com',null,null,null,null,null,null),
  ('taynasantiago7618@gmail.com','Pediatria','Campo Grande','MS','Pediatria',null,null),
  ('drathaiscassaroadm@gmail.com','Ginecologia','Aracruz','ES','Gineco e obstetra',null,null),
  ('drathaismendess@gmail.com','Ginecologia','Feira de Santana','BA','Ginecologista',null,null),
  ('vaneska37@gmail.com',null,null,null,null,null,null),
  ('vcorreamed97@gmail.com','Nutrologia','São José dos Campos','SP','Nutrólogo',null,null),
  ('vitoorkern@gmail.com',null,null,null,null,null,null),
  ('yaratrigo@hotmail.com','Ginecologia','Vitória','ES','Ginecologista',null,null),
  ('aguinaldojsfilho@gmail.com','Anestesiologia','Palmas TO','TO','Anestesia e dor',null,null),
  ('alo_jere@hotmail.com','Clínica Geral','Paulo Afonso Bahia',null,'Médico Generalista',null,null),
  ('amandanercolini@gmail.com',null,null,null,null,null,null),
  ('amandamed10@gmail.com',null,null,null,null,null,null),
  ('dra.ana.flavia@hotmail.com',null,null,null,null,null,null),
  ('analianaarrais@gmail.com','Ginecologia','Fortaleza/Ceara',null,'Ginecologista com foco em mulheres 35+ e ginecologista regenerativa',null,null),
  ('algaviao@hotmail.com','Ginecologia','Goiânia- Goias',null,'Ginecologia e Nutrologia(Clinica Afeto)',null,null),
  ('andrezadinizbh@hotmail.com',null,null,null,null,null,null),
  ('dra.bibianamisumi@gmail.com','Ginecologia','São José dos Campos, SP,',null,'Ginegologista',null,null),
  ('brunosouzafaria94@gmail.com','Ginecologia','Brasília',null,'Ginecologia, obstetrícia e Ultrassonografia',null,null),
  ('caiocordeiro14@hotmail.com','Emagrecimento e Metabolismo','Maceió AL','AL','Emagrecimento e Reposição Hormonal',null,null),
  ('camilaaraujooliveira@yahoo.com.br','Nutrologia','Montes Claros MG','MG','Nutrologa',null,null),
  ('camilazattaa@gmail.com','Nutrologia','Vitoria ES','ES','Nutrologa',null,null),
  ('dailorenago@gmail.com','Ginecologia','Brasilia- DF','DF','Ginecologista',null,null),
  ('dtlopes@gmail.com',null,null,null,null,null,null),
  ('esteladalben@gmail.com','Ginecologia','Porto Alegre - RS','RS','Ginecologista e Obstetra',null,null),
  ('fernanda_palhares@yahoo.com.br','Ginecologia','Araguaína-TO','TO','Ginegologista',null,null),
  ('flavinhahcsi@hotmail.com','Nutrologia','Santo André SP','SP','Nutrologa e Medicina Preventiva',null,null),
  ('gabriel_comerio@hotmail.com',null,null,null,null,null,null),
  ('geniapithon@outlook.com','Nutrologia','São Paulo - Vila Olímpia e Morumbi',null,'Nutrologia e Endocrinologia',null,null),
  ('ginandasanchez@gmail.com','Nutrologia','Tangará da Serra-MT','MT','Clínica geral: pós em Medicina de saúde da família, Perita Federal (sai dos desses vínculos) Pós graduação em Nutrologia',null,null),
  ('giselemotta@uol.com.br','Endocrinologia','Guarulhos- SP','SP','Endocrinologista',null,null),
  ('munhoz.iga88@gmail.com','Clínica Geral','Maceio Alagoas',null,'Clinica Medica',null,null),
  ('italo.gmv@gmail.com','Ginecologia','Salvador',null,'Ginecologista e Obstetra',null,null),
  ('nunesjoselia@gmail.com','Ginecologia','Bralisia-DF','DF','Ginecologista e Mastologista, com foco em Climatério e Menopausa',null,null),
  ('dra.julianameyer@gmail.com','Endocrinologia','Campinas- SP','SP','Endocrinologia e Medicina Integrativa',null,null),
  ('juliocesardelucafilho@gmail.com',null,null,null,null,null,null),
  ('karennrocha@hotmail.com','Medicina do Esporte','Manaus - AM','AM','Medicina do Esporte',null,null),
  ('karinamoniquea@hotmail.com','Clínica Geral','Petrolina-PE','PE','Médica generalista',null,null),
  ('papst.lari@gmail.com','Emagrecimento e Metabolismo','Brooklin',null,'Emagrecimento, saude metabólica e procedimento de estética',null,null),
  ('layllabreve@gmail.com','Ginecologia','Brasilia',null,'Ginecologista',null,null),
  ('liviaescobar16@gmail.com','Nutrologia','São Pulo /Alphaville',null,'Nutrologia e Medicina Integrativa',null,null),
  ('luana_limalima@outlook.com','Nutrologia','Ivinhema MS','MS','Nutrologia',null,null),
  ('luannagvleitec@gmail.com','Endocrinologia','Petrolina- PE','PE','Pós graduação Endocrinologia',null,null),
  ('drlucas_a_campagnaro@gmail.com','Nutrologia','Venda nova do imigrante - ES','ES','Ortopedia e traumatologia Medicina esporte Nutrologia',null,null),
  ('drlucasma1994@gmail.com',null,null,null,null,null,null),
  ('ludi.med@gmail.com',null,null,null,null,null,null),
  ('dra.luisevila@gmail.com',null,null,null,null,null,null),
  ('drcaetano7@yahoo.com.br','Ginecologia','Região Metropolitana de Campinas-SP','SP','Ginecologia',null,null),
  ('ggertrudesouriquesteles@gmail.com','Ginecologia','Sobral- CE','CE','Ginecologista focado em menopausa e emagrecimento',null,null),
  ('mariaisabel.consultorio@gmail.com','Ginecologia','Moema- SP','SP','Ginegologista',null,null),
  ('jutaio@hotmail.com','Medicina do Esporte','Taiobeiras MG','MG','Medicina Esportiva',null,null),
  ('paolalmuniz@hotmail.com','Endocrinologia','maringa Pr','PR','endocrinologista',null,null),
  ('drapatriciarezende@gmail.com','Emagrecimento e Metabolismo','Caiapônia- GO','GO','Obesidade e Medicina Integrativa',null,null),
  ('piaranas@gmail.com','Ginecologia','Ribeirão Preto- SP','SP','Medicina do Espote e Ginecologia Endócrina',null,null),
  ('rafaelly.rd@gmail.com','Ginecologia','Fortaleza-CE','CE','Ginecologia e Obstetricia',null,null),
  ('silviaval13@gmail.com','Nutrologia','Jardins - SP','SP','Nutrologa',null,null),
  ('drasinaracastro@yahoo.com.br','Ginecologia','Goiânia Goiás',null,'Ginegologista',null,null),
  ('drasofiagpereira@gmail.com','Endocrinologia','Rio de Janeiro','RO','Endocrinologia',null,null),
  ('soniagasparoni.endocrino@gmail.com',null,null,null,null,null,null),
  ('tati_lauria@hotmail.com','Ginecologia','Rio de Janeiro','RO','Ginecologia / regenerativa /endoscopia ginecológica',null,null),
  ('thaniacunha@yahoo.com.br','Ginecologia','Uberlândia MG','MG','Ginecologista',null,null),
  ('tuannycanedo@gmail.com','Ginecologia','São João do Piauí',null,'Ginecologista',null,null),
  ('victorsilva43@gmail.com',null,'colatina Espírito Santo','TO','ainda não tem',null,null),
  ('vilsonlm@hotmail.com','Ginecologia','Criciúma','SC','Ginecologista e Fertileuta, especialista em Reprodução Assistida pela Febrasgo(Crifert)',null,null),
  ('walterpitman@gmail.com',null,null,null,null,null,null),
  ('drawanessastival@gmail.com','Endocrinologia','Brasília',null,'Endocrinologista',null,null),
  ('gomeswilton50@yahoo.com',null,null,null,null,null,null),
  ('poliandrade15@hotmail.com','Ginecologia','Rio de Janeiro','RO','Ginecologia',null,null),
  ('aliciacimada@gmail.com','Nutrologia','Rio de janeiro','RO','Nefrologista e Nutróloga',null,null),
  ('mari.gregolini@gmail.com',null,null,null,null,'SIM','SIM'),
  ('riosnaor@gmail.com',null,null,null,null,'SIM','SIM'),
  ('begwicks@uol.com.br',null,null,null,null,'SIM','SIM'),
  ('thaysec@gmail.com',null,null,null,null,'SIM','SIM'),
  ('amisbele@gmail.com',null,null,null,null,'SIM','SIM'),
  ('drbogos61@hotmail.com',null,null,null,null,'NÃO','mandou via whatsapp'),
  ('financeiro@nucleofw.com',null,null,null,null,'NÃO','Respondeu via whatsapp'),
  ('mayveloza@hotmail.com',null,null,null,null,'SIM','NÃO'),
  ('barbaracastromuniz@gmail.com',null,null,null,null,'SIM','SIM'),
  ('eduardoalencar_duda@hotmail.com',null,null,null,null,'NÃO','Respondeu via whatsapp'),
  ('danielamra@hotmail.com',null,null,null,null,'SIM','NÃO'),
  ('consultorioafra@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('gardcenci@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('clinicabogossian@hotmaill.com',null,null,null,null,'NÃO','Ia ir, mas teve um imprevisto(mandou via whatsapp)'),
  ('ferrazfc@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('drbrunopeixoto1@gmail.com',null,null,null,null,'NÃO','respondeu via whatsapp'),
  ('anaramirez@terra.com.br',null,null,null,null,'NÃO','respondeu via whatsapp'),
  ('carmenaraujolima@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('alhender.bridi@hotmail.com',null,'São Paulo',null,null,'SIM','SIM'),
  ('amanda_bissoli@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('tinabatalha8@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('andreatanuri@gmail.com',null,null,null,null,'SIM','SIM'),
  ('doutorabrunasantos@hotmail.com',null,null,null,null,'NÃO','NÃO'),
  ('caioatps@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('camilagiannecchini@gmail.com',null,null,null,null,'NÃO','NÃO'),
  ('contato@dracathycoelho.com','Mastologia','São paulo',null,'Mastologista','NAO RESPONDEU','NAO RESPONDEU'),
  ('crismac19@yahoo.com.br','Nutrologia','Uberlândia',null,'ortopedia e nutrologia','NAO RESPONDEU','NAO RESPONDEU'),
  ('cbreval79@gmail.com','Nutrologia','Amazonas',null,'Nutrologia','SIM','NÃO'),
  ('clinicamater@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('divinomed@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('dredgarsarmento@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('soccoljr@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('eduardopachu350@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('erikadfj@gmail.com',null,null,null,null,'SIM','SIM'),
  ('draesthela@sideclinic.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('fbalem@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('fernandabrunomacedo@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drafernadasd@gmail.com',null,null,null,null,'SIM','SIM'),
  ('gabrielmattos@msn.com',null,null,null,null,'SIM','SIM'),
  ('drageciele@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('giselle_rm@hotmail.com','Ginecologia','São José dos Campos - SP','SP','Ginecologia e obstetrícia','SIM','SIM'),
  ('hperesrocha@gmail.com',null,null,null,null,'NÃO','NAO RESPONDEU'),
  ('higorcaldato@outlook.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drahilloa@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('gestaodrjoaolauro@gmail.com',null,null,null,null,'NÃO','NAO RESPONDEU'),
  ('pereirajordana94@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drajuliana@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('katianaturon@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('kelso@kelsopassos.com.br','Ginecologia','Aracaju',null,'Ginecologista e obstetra','SIM','NÃO'),
  ('lecianaramos@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('livinhaninno@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drlucasmirandabessa@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('lucio@grapeclinic.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('luisafernasopolis@hotmaik.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drluissguedes@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('luizdcrf@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('marcela@grapeclinic.com.br',null,null,null,null,'SIM','SIM'),
  ('marciagineco@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('marcosvinicius@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('mcrosenbaum@outlook.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('malemosps@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('maryvalves@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('marielalmuniz@yahoo.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('marinamtbarboza@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drlemosmatheus@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('mayaralanucy@hotmail.com',null,null,null,null,'NÃO','NAO RESPONDEU'),
  ('melvivi5@gmail.com',null,null,null,null,'SIM','SIM'),
  ('merencianaduarte@gmail.com',null,null,null,null,'SIM','SIM'),
  ('michelle.phe27@yahoo.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('nathidalpra@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drapatriciacavalcante@yahoo.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('magierpatricia@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('dr.pauloabreu@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('pedrohluiz27@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('pedrotakiuti@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drapriscilanascimento63@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('rebellodraregina@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('smachado60@yahoo.com',null,null,null,null,'SIM','NÃO'),
  ('saritarods@yahoo.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drasuzanalessaplano@gmail.com',null,null,null,null,'SIM','SIM'),
  ('talitalelis2017@gmail.com',null,null,null,null,'NÃO','NAO RESPONDEU'),
  ('thiago@drthiagocollares.com',null,'Balneário Camburiú',null,'Não tem especialidade','NAO RESPONDEU','NAO RESPONDEU'),
  ('thiagopereiramed@yahoo.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('twoany86@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('medicinavitalis@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('nettoninno12@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('aleleby@yahoo.com.br',null,null,null,null,'SIM','SIM'),
  ('sofiaccalheiros@yahoo.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('arubiap@gmail.com',null,null,null,null,'SIM','SIM'),
  ('anec.barreto.302@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('drabrendamendonca@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('dracarlafreitas@outlook.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('carolmsstarling@yahoo.com.br',null,null,null,null,'SIM','SIM'),
  ('dandaratureta@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drdanielteixeira@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('dradelmanevesnutro@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('ftanuri@yahoo.com.br',null,null,null,null,'SIM','SIM'),
  ('contato@clinicajulianaaliprandi.com.br',null,null,null,null,'SIM','SIM'),
  ('karinerantunes@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('contato@drakatiaramos.com.br',null,null,null,null,'SIM','SIM'),
  ('kennya_1104@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('tonelkezia@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('lanakris@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('lsilvaesilva@yahoo.com.br',null,null,null,null,'SIM','NÃO'),
  ('leidynx1@outlook.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drleonardopozzobon@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('doutoralise@gmail.com',null,null,null,null,'SIM','SIM'),
  ('draliviatrevisan@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('lorenafernandesmelof@gmail.com',null,null,null,null,'NÃO','NÃO'),
  ('fc.luaira@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('lucasmissiba@hotmail.com',null,null,null,null,'NÃO','NÃO'),
  ('ludeister@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('lux.tempesta@uol.com.br',null,null,null,null,'SIM','SIM'),
  ('lfcastroneves@gmail.com',null,null,null,null,'SIM','SIM'),
  ('drluizmichels@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('marcelafilgueiras@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('masj83@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('mariapaula.mourac@gmail.com',null,null,null,null,'SIM','SIM'),
  ('dr.matheusdeon@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('mauriciofriederich@yahoo.com.br',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('miamfurlan@gmail.com',null,null,null,null,'SIM','SIM'),
  ('mmbuzzato@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('natalia.fioramonte@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('natani_espinosa@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('pamella.alves@yahoo.com.br',null,null,null,null,'SIM','SIM'),
  ('paulaavel@gmail.com',null,null,null,null,'NÃO','NÃO'),
  ('paula_machadomed@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('doutor.mantoan@gmail.com',null,null,null,null,'SIM','SIM'),
  ('rachelsouto@gmail.com',null,null,null,null,'SIM','SIM'),
  ('filgueirasrebeca@yahoo.com.br',null,null,null,null,'SIM','NÃO'),
  ('re_fernandes66@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drarenatagabrielly@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drridelson@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('robertamiele@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('robertocesarleite15@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('digo_irece@gmail.com',null,null,null,null,'SIM','SIM'),
  ('romolo.guida@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('rosana_rassi@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drasamaralima@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('sara_ulhoa@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('sivalle@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('sinara.v.p@hotmail.com',null,null,null,null,'NÃO','NÃO'),
  ('tainadurans@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drataniamariacarvalho@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('thaipaulucci@gmail.com',null,null,null,null,'SIM','SIM'),
  ('drathalitasc@gmai',null,null,null,null,'NÃO','NÃO'),
  ('drverissimoendocrino@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('vi-sacchetto@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('viviandani.bastos@gmail.com',null,null,null,null,'SIM','SIM'),
  ('viviannpecly@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('drwellingtonreis@outlook.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('wilsonbbsampaio@hotmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('drayole.endorclinica@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('zelmavilasboas@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('rafaela.nlbc@gmail.com',null,null,null,null,'NAO RESPONDEU','NAO RESPONDEU'),
  ('dra.valeria@clinicavalerialeal.com.br',null,null,null,null,'SIM','NÃO'),
  ('maisafukayama@hotmail.com',null,null,null,null,'SIM','NÃO'),
  ('anne.karoline.ferreira@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('graziellyteles@hotmail.com.br',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('camillaclc@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('etianneandradec@gmail.com',null,null,null,null,'SIM','SIM'),
  ('clinicadrguilhermelobo@gmail.com',null,null,null,null,'SIM','SIM'),
  ('drajanainaborges@gmail.com',null,null,null,null,'SIM','SIM'),
  ('claudiohenriquealegrebrito@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('contato@drdiegosilva.com.br',null,null,null,null,'SIM','NÃO'),
  ('dracamilabandeira@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('claudia@dracaludia.com.br',null,null,null,null,'SIM','SIM'),
  ('vanessafraifeand@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('simoes_florio@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('carolinaborgesduarte@gmail.com',null,null,null,null,'NÃO','NÃO'),
  ('challsiesuzarte@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('dqjobst@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('lucineidemmaia@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('nandanq.cabral@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('karolinetorresmed@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('crisnavarro83@yahoo.com.br',null,null,null,null,'SIM','SIM'),
  ('drajessicasrepolho@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('dramanuelamcz@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('gabrielbastos@yahoo.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('georgianagama07@gmail.com',null,null,null,null,'SIM','SIM'),
  ('andressa.brunelli@hotmail.com',null,null,null,null,'NÃO','NÃO'),
  ('getuliojs@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('arthurbarros2@gmail.com',null,null,null,null,'SIM','SIM'),
  ('ingridlima-25@hotmail.com',null,null,null,null,'SIM','NÃO'),
  ('gynederme@gmail.com',null,null,null,null,'SIM','SIM'),
  ('igorbalves@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('drakarline@gmail.com',null,null,null,null,'SIM','SIM'),
  ('hellena.gabriella@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('dr.diegofernando99@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('brunolandin@yahoo.com.br',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('izabelarezende10@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('katrinarocha02@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('fabiolapfrotamed@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('flavia.alves.m@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('bmourasousa@yahoo.com.br',null,null,null,null,'NÃO','NÃO'),
  ('edaianefranco@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('edmo_galvao@hotmail.com',null,null,null,null,'SIM','SIM'),
  ('enfnetto@yahoo.com.br',null,null,null,null,'NÃO','NÃO'),
  ('carlosbronzel@hotmail.com',null,null,null,null,'NÃO RESPONDEU',null),
  ('contato@dragabrielabecker.com',null,null,null,null,'SIM','SIM'),
  ('dra.anacarolinarocha@outlook.com',null,null,null,null,'NÃO','NÃO'),
  ('cristianepsaguiar@gmail.com',null,null,null,null,'SIM','SIM'),
  ('esteticalaseraf@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('bellaclin@hotmail.com',null,null,null,null,'SIM','NÃO'),
  ('dra.elinesoriano@gmail.com',null,null,null,null,'SIM','NÃO'),
  ('freitasjoaopaulo@hotmail.com',null,null,null,null,'SIM','NÃO'),
  ('cibelepimentel.ciclinic@yahoo.com.br',null,null,null,null,'SIM','SIM'),
  ('biazillmer@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('indymed@live.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('marcos_opa@yahoo.com.br',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('jessika_katriny@hotmail.com',null,null,null,null,'SIM','NÃO'),
  ('ccybelee@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('elisabetemrp@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('drfredcorte@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('isadoramachadodeoliveira@hotmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('luannagpperea@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('bpfranca@yahoo.com.br',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('go.anacsiqueira@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('mcrconsultorio@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('ypcserra@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('dralexbarros@gmail.com',null,null,null,null,'NÃO RESPONDEU','NÃO RESPONDEU'),
  ('dra.camila@clinicacasapaes.com.br',null,null,null,null,null,null),
  ('gabrielalaboissiere@gmail.com',null,null,null,null,null,null),
  ('luiscngarcia@gmail.com',null,null,null,null,null,null),
  ('dramarilia.vaz@gmail.com',null,null,null,null,null,null),
  ('pauladscorrea@gmail.com',null,null,null,null,null,null),
  ('rominaendocrino@gmail.com',null,null,null,null,null,null),
  ('donatti.a.x@gmail.com',null,null,null,null,null,null),
  ('drmichaelcaminha@gmail.com',null,null,null,null,null,null),
  ('marcelamedufu@gmail.com',null,null,null,null,null,null),
  ('nandalimafls@gmail.com',null,null,null,null,null,null),
  ('gustavocaldeiradr@gmail.com',null,null,null,null,null,null),
  ('manoelapietro91@gmail.com',null,null,null,null,null,null),
  ('dradeborahschmitt@gmail.com',null,null,null,null,null,null),
  ('fernandaabirihan@gmail.com',null,null,null,null,null,null),
  ('juliapabrahao95@gmail.com',null,null,null,null,null,null),
  ('raquelssito@hotmail.com',null,null,null,null,null,null),
  ('renataortiz3@hotmail.com',null,null,null,null,null,null),
  ('wilsonmarquesam@gmail.com',null,null,null,null,null,null),
  ('dandaralacerda@hotmail.com',null,null,null,null,null,null),
  ('fernandafernandesm@hotmail.com',null,null,null,null,null,null),
  ('amandadearruda@hotmail.com',null,null,null,null,null,null),
  ('juliananoronhapinheiro@gmail.com',null,null,null,null,null,null),
  ('lukstosi@hotmail.com',null,null,null,null,null,null),
  ('andrecasteloes@hotmail.com',null,null,null,null,null,null),
  ('dr.cleissonborges@gmail.com',null,null,null,null,null,null),
  ('danyafreitas@hotmail.com',null,null,null,null,null,null),
  ('joaopaulovitorino@hotmail.com',null,null,null,null,null,null),
  ('jonascortez@nutriterapica.com',null,null,null,null,null,null),
  ('kkmontenegroc@gmail.com',null,null,null,null,null,null),
  ('karolinalencar.med@gmail.com',null,null,null,null,null,null),
  ('marco.rmoraes@gmail.com',null,null,null,null,null,null),
  ('marinamreis@yahoo.com.br',null,null,null,null,null,null),
  ('frias@cardiol.br',null,null,null,null,null,null),
  ('ronaldoborgesmendes@gmail.com',null,null,null,null,null,null),
  ('drasabrinaribeironutro@gmail.com',null,null,null,null,null,null)
on conflict (email) do nothing;

update students s set
  especialidade          = coalesce(p.especialidade, s.especialidade),
  especialidade_original = coalesce(p.especialidade_original, s.especialidade_original),
  cidade                 = coalesce(p.cidade, s.cidade),
  uf                     = coalesce(p.uf, s.uf),
  cidade_uf              = coalesce(nullif(trim(coalesce(p.cidade,'') || case when p.uf is not null then '/' || p.uf else '' end), ''), s.cidade_uf)
from dados_extras p
where lower(s.email) = p.email;

create index if not exists students_uf_idx on students (uf);
create index if not exists students_esp_idx on students (especialidade);

notify pgrst, 'reload schema';

-- conferência
select count(*) filter (where especialidade is not null) as com_especialidade,
       count(*) filter (where uf is not null)            as com_estado,
       count(distinct especialidade)                     as especialidades,
       count(distinct uf)                                as estados
  from students where status in ('ativo','trancado');

select especialidade, count(*) from students
 where status = 'ativo' and especialidade is not null
 group by 1 order by 2 desc;

select uf, count(*) from students
 where status = 'ativo' and uf is not null
 group by 1 order by 2 desc;
