-- v61: respostas da pesquisa de NPS (formulário do Google) dentro do sistema.
-- 152 respostas, escala de 0 a 5. A nossa tabela é 0-10, então guardamos a nota
-- original em `score_raw` + a escala, e `score` fica normalizado pra 0-10
-- (nota 5 = 10). Assim o cálculo de promotor/detrator continua valendo e a CS
-- vê a nota como o aluno respondeu.

-- Resposta de quem não achamos na base (nome escrito diferente, ou pessoa que
-- não é aluno) também precisa ser guardada: fica sem aluno e a CS liga depois.
alter table nps_responses alter column student_id drop not null;

-- A coluna `source` tem uma regra que só aceita os valores antigos. Recria a
-- regra somando o que já existe na tabela + as origens novas, sem perder nada.
do $$
declare vals text;
begin
  select string_agg(distinct quote_literal(source), ', ') into vals
    from nps_responses where source is not null;
  vals := coalesce(vals || ', ', '') || quote_literal('pesquisa_2026_08') || ', ' ||
          quote_literal('primeiro_acesso') || ', ' || quote_literal('periodico') || ', ' ||
          quote_literal('planilha');
  execute 'alter table nps_responses drop constraint if exists nps_responses_source_check';
  execute 'alter table nps_responses add constraint nps_responses_source_check check (source is null or source in (' || vals || '))';
end $$;

alter table nps_responses add column if not exists scale            int;
alter table nps_responses add column if not exists score_raw        int;
alter table nps_responses add column if not exists respondent_name  text;
alter table nps_responses add column if not exists mentoria_informada text;
alter table nps_responses add column if not exists motivo           text;
alter table nps_responses add column if not exists melhorar         text;
alter table nps_responses add column if not exists feedback_geral   text;
alter table nps_responses add column if not exists instagram        text;

-- staging
drop table if exists pesquisa_nps;
create table pesquisa_nps (
  respondido_em timestamptz, nome text, chave text, mentoria text,
  nota int, motivo text, melhorar text, feedback_geral text, instagram text
);
insert into pesquisa_nps (respondido_em,nome,chave,mentoria,nota,motivo,melhorar,feedback_geral,instagram) values
  ('2026-08-24 17:24:50-03'::timestamptz,'Claudia Regina Simões Rodrigues Pedroso','claudia regina simoes rodrigues pedroso','Mentoria Mãe',5,'A entrega ale do prometido','Suponho que a melhoria está a caminho com mais hands on de implantes.','Uma aula sempre supera a outra, sempre com atualizações em primeira mão.E o básico não é esquecido.','@draclaudiarodrigues'),
  ('2026-08-24 22:19:38-03'::timestamptz,'Analiana Alencar Arrais de Souza','analiana alencar arrais de souza','Ativação',3,'Falta de acompanhamento e orientação','Aulas específicas em horários viáveis. Tira dúvidas as 07/00 da manhã é impossível. Nunca vi em nenhuma outra mentoria','Aulas gravadas boas . Apoio dos professores muito pouco. Discussões os grupos muito básica. Mistura que tem noções de TH até por ser Gineco com pessoas que só concluíram o curso de medicina. Não tem tido muito acréscimo de conhecimento','Dra.analianaarrais'),
  ('2026-08-25 08:26:24-03'::timestamptz,'Tuanny Canedo','tuanny canedo','Ativação',5,'Ótima tratativa aos alunos','Acho os valores mentorias muito caras','Material muito bom','Dratuannycanedo'),
  ('2026-08-25 10:14:18-03'::timestamptz,'Gustavo Magalhães Coimbra','gustavo magalhaes coimbra','Surgical',4,'Produto muito bom, entrega excelente.','Aulas mais claras sobre a parte hormonal, onde tenho mais dificuldade. Gostaria de mais material escrito, por na aula muitas vezes um assunto encavala no outro, perdemos o fio do raciocínio e muitas vezes a abordagem fica superficial, gostaria de uma parte mais estruturada.','Aulas boas, suporte excelente !','@coimbragustavo'),
  ('2026-08-25 10:29:52-03'::timestamptz,'THAIS MENEZES CARDOSO','thais menezes cardoso','Start Caio e Jordana',5,'Mentoria abrangente com ofertando conhecimento técnico, como estrutura a clínica e mentalidade de sucesso.','Na mentoria start fazer mais reavaliações individualizadas com os mentorandos.','Tudo excelente.','dra.thais.menezes'),
  ('2026-08-25 10:48:56-03'::timestamptz,'Karina Carolina de oliveira','karina carolina de oliveira','Mentoria Mãe',5,'Maestria','Organização dos grupos, sao mtos grupos com muita gente falando. Informação fica perdida.','Amo os meninos 🩵🩵','drakarinacarolina'),
  ('2026-08-25 11:14:27-03'::timestamptz,'Bruna Francielli Pereira Santos hryniewicz','bruna francielli pereira santos hryniewicz','Mentoria Mãe',5,'Ótimo ecosistema entrega boa, atualização estudo científico','Acho que ter um olhar mais individual de cada médico dentro da realidade de cada médico.','Acho ótimos','Drabrunasantoshryniewiz'),
  ('2026-08-25 12:28:36-03'::timestamptz,'Bruno Mota','bruno mota','Surgical',4,'Entrega','Menos pitch de vendas nas aulas extras está muito intenso isso e diminui o conteúdo','Excelente','@dr.brunomota'),
  ('2026-08-25 12:35:44-03'::timestamptz,'Cibele Lemos Lacerda','cibele lemos lacerda','Surgical',5,'Tenho ajuda sempre que preciso','Plataforma tem aulas muito antigas misturadas com Novas.','O grupo de WhatsApp está com muitas pessoas. Percebi que aumentou muito o volume de mensagens e não Consigo acompanhar todas. Mas sempre sou respondida nas minhas dúvidas.','@dracibelelemos'),
  ('2026-08-25 13:01:50-03'::timestamptz,'Fabiane Zillmer','fabiane zillmer','Mentoria Mãe',5,'Compromisso da Endogin com seus alunos','As respostas do Whats, eu acredito que a demanda seja muita p Dr Caio','Aulas maravilhosas','drafabianezillmer'),
  ('2026-08-25 15:22:56-03'::timestamptz,'Maria Gertrudes Ouriques Teles','maria gertrudes ouriques teles','Ativação',5,'Grupo acima das minha expectativas sobre todos os aspectos no que diz respeito a crescimento pessoal, técnico e financeiro.Tudo de BOM!!','Não eh tão acessível. Mas, tudo bem, o preço fala tbem de posicionamento e percepção de valor.Nao separem “ os cafezinhos” durante os cursos, fica muito estranho., mesmo que seja do seu conhecimento o que eh ou nao de direito…','Aulas abordando vários temas, revisões científicas atualizadas. Excelente conteúdo programático.Tem que haver mais Hands On ( Implantes), que não eh o meu caso pessoal, mas para a galera que tá iniciando.','@gertrudesouriques'),
  ('2026-08-25 18:21:39-03'::timestamptz,'Giorgio Baretta','giorgio baretta','Surgical',5,'Estou super satisfeito','No momento nada','100% feliz','@drgiorgiobaretta'),
  ('2026-08-25 18:22:45-03'::timestamptz,'Ingryd Amaral Nóbrega','ingryd amaral nobrega','Mentoria Mãe',5,'Por já conhecer Caio e por ter participado do Último evento. Passei dois anos Com Gabriel e a mentoria de Caio e Vinicius é muito Superior','Acho que vai chegar a hora de aprender mais Sobre coisas que ainda tenho dúvida tirando Isso está sendo maravilhosa','Maravilhoso','Dra.Ingrydnobrega'),
  ('2026-08-25 19:15:41-03'::timestamptz,'Jonas Cortez Moreira Junior','jonas cortez moreira junior','Mentoria Mãe',5,'Conteúdo técnico, conteúdo de mentalidade e espiritualidade.','Depois do onboarding fazer um contato de acompanhamento individual.','Aulas fantásticas, professores excelentes, material de apoio excelente. Só gratidão! Sei que quem ficou a desejar fui eu mesmo.','@jonascortezmjr'),
  ('2026-08-25 19:28:11-03'::timestamptz,'Marcos Roberto Caetano','marcos roberto caetano','Ativação',5,'Qualidade das aulas e ética profissional','Entendo que a ativação mesmo sendo um produto de entrada está muito aquém dos demais produtos do ecossistema da endogin. Inclusive com relação ao acesso das aulas e outras situações dentro da plataforma. No ativação além de dois encontros mensais de dúvidas o que temos é poder estudar no material gravado e limitar este acesso diminui ainda mais um produto que já é limitado','Masterclass muito boas, o material de apoio acessível é bom ( mas já com pontos ultrapassados como o que está disponível de início de 2025 e não atualizado com atualização recentes). Os professores de apoio são dedicados e engajados na missão. A Evelyn como apoio sempre pronta a ajudar, mas também com limitações impostas pelo formato do produto ativação. Como já tive oportunidade de pessoalmente solicitar que seja revisto o que o ativação tem oferecido de entrega.','@drmarcoscaetano'),
  ('2026-08-25 19:29:36-03'::timestamptz,'Paula Avelar Marquez','paula avelar marquez','Mentoria Mãe',5,'Excelência nas áreas a que se propõe','Discussões dos grupos voltarem','Sinto falta de mais artigos e temas adjacentes à reposição hormonal (osteoporose, trh pós câncer de mama, trh pós iam, trh pós AVC, trh na mulher com TAB/depressao)','Dra Paula Marquez'),
  ('2026-08-25 21:00:47-03'::timestamptz,'Andrea Perfeito','andrea perfeito','Mentoria Mãe',5,'Meus resultados','Mais Parcerias com fornecedores','Aulas ótimas , material de apoio muito bom e professores ótimos','Draandreaperfeito'),
  ('2026-08-25 23:54:46-03'::timestamptz,'Afra Maria Mendes Barbosa','afra maria mendes barbosa','Mentoria Mãe',5,'Entrega de conhecimentos e coração!','Não mudar a essência do servir !','Aulas , Materiais, professores , tudo excelentes !!','Continuar sendo luz'),
  ('2026-08-26 14:17:00-03'::timestamptz,'Rafaela Nunes Lira Braga Cândido','rafaela nunes lira braga candido','Mentoria Mãe',5,'Tudo','No momento não sei responder essa pergunta','Maravilhosos','@rafaela_nunes'),
  ('2026-08-26 14:38:06-03'::timestamptz,'Merenciana Sarkis','merenciana sarkis','Mentoria Mãe',5,'Jesus como mestre de tudo. Base científica, seguro na conduta médica, proximidade e disponibilidade dos mentores conosco','Adequar a nossa realidade de vendas individual do que temos e ainda não temos de vendas ou pacientes','Excelentes!','@drameryduarte'),
  ('2026-08-26 15:12:08-03'::timestamptz,'MARCOS SANCHES','marcos sanches','Mentoria Mãe',5,'SATISFAÇÃO','RESGATAR A PROXIMIDADE COM OS MENTORADOS','MENYORIA EXCELENTE, CONTEÚDO EXCEPCIONAL','dr.marcossanches_'),
  ('2026-08-26 17:22:49-03'::timestamptz,'Marcos Oliveira Pires de Almeida','marcos oliveira pires de almeida','Mentoria Mãe',5,'Pela qualidade do que é entregue','Oferecer aulas de vendas mais focadas pra quem tem faturamento mais baixo ainda, não apenas focadas pra quem já fatura várias centenas de milhares de reais.','Aulas quase sempre excelentes.','@drmarcosendocrino'),
  ('2026-08-26 17:43:57-03'::timestamptz,'ANÍBAL DA TORRE BOGOSSIAN','anibal da torre bogossian','Mentoria Mãe',5,'Eficiência','Abranger outras áreas da medicina','O conteúdo é muito importante e a facilidade com que transmitem seus conhecimentos','#dr.anibalbogossian'),
  ('2026-08-26 17:58:09-03'::timestamptz,'Maria Isabel Navarro Muccillo','maria isabel navarro muccillo','Ativação',4,'Só coloquei 4 porque acho que alguns médicos não tem o perfil de estar aberto a novos modelos e a entender que faturamento na medicina não é errado, é justo, merecimento.','Talvez material de apoio tipo pdf.','Positivo, mentores entregam muito, estou começando mas já está sendo ótimo.','@dramariaisabelmuccillo'),
  ('2026-08-26 19:15:45-03'::timestamptz,'Thalita Carvalho','thalita carvalho','Mentoria Mãe',5,'Pela entrega técnica','Reduzir um pouco os encontros ! Impossível assistir todas as aulas .','Gostaria de deixar uma crítica construtiva em relação à Endogin. Tenho percebido que várias aulas extras, como tratamento capilar, peptídeos e outros temas, acabam sendo direcionadas para a venda de novos cursos. O investimento que fazemos na Endogin mãe já é bastante significativo, e acredito que conteúdos complementares e atualizações poderiam fazer parte dessa formação de maneira mais completa. Ultimamente, tenho a sensação de que muitas oportunidades de aprendizado dentro da própria Endogin acabam se transformando em uma nova oferta comercial. Entendo que existam cursos de aprofundamento, mas acho importante haver um equilíbrio entre entregar conteúdo para quem já investiu na formação e oferecer novos produtos. Como aluna, isso tem me gerado um certo incômodo e acredito que seja um feedback válido para reflexão.','@dra.thalitacarvalho'),
  ('2026-08-26 21:08:11-03'::timestamptz,'Silvia Valdemarin Alves','silvia valdemarin alves','Ativação',4,'Como entrei recentemente ainda não consegui assistir todo o conteúdo, porém estou gostando muito dos conteúdos apresentados.','Ainda não tive tempo suficiente para conhecer toda a estrutura e vivenciar a experiência toda para apontar melhorias com propriedade.','Tudo ótimo.','@drasilviavaldemarin'),
  ('2026-08-26 22:47:27-03'::timestamptz,'Marcio Schenato','marcio schenato','Surgical',5,'Mentores com grande conhecimento e sempre muito solícitos e dispostos a ajudar e resolver todas as dificuldades.','Incluir inteligência artificial e ensinar como podemos utilizar da melhor forma em nossa atividade profissional','Entrei na mentoria em Novembro/2025 e o material de apoio estava desorganizado, mas evoluiu muito e rapidamente. Em relação aos professores só tenho elogios, principalmente a Jordana e Caio, que entraram na Surgical após a saída do Dr Rogério. No início não achei legal essa troca repentina, inclusive cheguei a pensar em sair da mentoria. Mas agora já tenho certeza que vou renovar em Novembro justamente pela presença dos dois, que realmente me fizeram evoluir no conhecimento','marcio_schenato'),
  ('2026-08-27 11:41:34-03'::timestamptz,'Fabiano Tanuri','fabiano tanuri','Mentoria Mãe',5,'Entrega da equipe','Mais sobre a parte masculina','Mentoria excelente','@fabianotanuri'),
  ('2026-08-27 11:44:14-03'::timestamptz,'Fabíola Frota','fabiola frota','Mentoria Mãe',5,'Entrega e acesso aos mentores','Material escrito / PDF das aulas mais técnicas','Amo a mentoria !','drafabiolapfrota'),
  ('2026-08-27 12:10:53-03'::timestamptz,'Ronaldo Borges','ronaldo borges','Mentoria Mãe',5,'Muitos','Parar de querer colocar produtos a mais que deveriam ser da própria entrega como gestão , peptídeos , tricologia ( teórica básica claro) , etc','Só agradecer e dizer que conto com eles para melhorar e virar de vez a questão hormonal/ performance','@drronaldoborges'),
  ('2026-08-27 12:12:30-03'::timestamptz,'HILLOA RODRIGUES PEREIRA','hilloa rodrigues pereira','Mentores Masters',5,'AMBIENCIA, QULAIDADE DE PROFISSIONAIS E PROPOSITOS','CRIAR BRAÇO DE MARKETING PARA AJUDAR A ATRAIR CLIENTES','É uma alegria fazer parte de um projeto que reúne profissionais incríveis e que nos inspira constantemente a evoluir e transformar nossa prática médica.','@DRAHILLOARODRIGUES.NUTROLOGA'),
  ('2026-08-27 12:19:05-03'::timestamptz,'Alexandre Florio','alexandre florio','Mentoria Mãe',5,'Minha experiência e o que vivo na mentoria','Continuar assim','Tudo perfeito','de.alexandreflorio'),
  ('2026-08-27 12:47:02-03'::timestamptz,'Vitoria Matioli Sacchetto','vitoria matioli sacchetto','Mentoria Mãe',5,'Sou muito satisfeita com a mentoria','Mais acesso aos meninos. Como no inicio da endogin.','Tudo maravilhoso','dravitoriasacchetto'),
  ('2026-08-27 13:37:32-03'::timestamptz,'Glauco Soares Maia Piassi','glauco soares maia piassi','Start Caio e Jordana',5,'Confiança','Conhecimentos sobre gestão e sobre atração de clientes.','Satisfeito.','drglaucopiassi'),
  ('2026-08-27 13:57:16-03'::timestamptz,'Thaisa Marques de Lima Bramusse','thaisa marques de lima bramusse','Start Caio e Jordana',4,'Alguns pontos a me lograr','Estou gostando muito da Mentoria, minha experiência tem sido muito positiva. Como ponto de melhoria, sinto que a parte de gestão ainda está deixando um pouco a desejar. Para mim, seria muito interessante se as aulas de terça-feira fossem mais direcionadas para gestão da clínica, processos, equipe, financeiro, estratégias comerciais e crescimento do negócio. Acredito que esse seja um dos grandes diferenciais que esperava encontrar na mentoria. Outro ponto que me incomoda um pouco é a quantidade de conteúdo entregue nas aulas gratuitas. Entendo que elas sejam importantes para divulgação e captação de novos alunos, mas, em alguns momentos, tenho a percepção de que é entregue muito conteúdo para quem não faz parte da mentoria, considerando o investimento significativo de quem optou por participar. Acho importante que fique mais evidente a exclusividade e o valor agregado de quem está dentro do programa. Também acredito que o calendário das aulas poderia ser mais organizado e intuitivo, pois às vezes acaba ficando um pouco confuso acompanhar a programação. Gostaria de sugerir a possibilidade de rever o horário das discussões de casos clínicos. Para mim, 18h30 ainda é um horário em que estou finalizando os atendimentos na clínica, o que dificulta bastante a participação ao vivo. Se fosse um pouco mais tarde, acredito que facilitaria não apenas para mim, mas também para outros médicos que atendem até o final do dia.','Coloquei acima','drathaisabramusse'),
  ('2026-08-27 14:07:53-03'::timestamptz,'FABIANO WINCKLER','fabiano winckler','Mentoria Mãe',5,'Entrega dos mentores','nada','tudo ótimo, material de apoio muito bom','@fawinckler'),
  ('2026-08-27 14:25:40-03'::timestamptz,'Luciana Tempesta','luciana tempesta','Mentoria Mãe',5,'Ecossistema maravilhoso','Sinceramente, não sei.','Aulas maravilhosas dos “ meninos “, dos professores Caio 2, Mamede, aula de mentalidade com muita humildade. Quero aprender a retirar implantes e atender na casa modelo. E o encontro na praia.','Dra Luciana Tempesta'),
  ('2026-08-27 14:28:10-03'::timestamptz,'Gardenia Cenci','gardenia cenci','Mentoria Mãe',5,'Ambiencia','Alunos terem acesso melhor a Biomeds 😅','Excelente','@dragardeniacenci'),
  ('2026-08-27 15:27:40-03'::timestamptz,'ZELMA MARIA DOS SANTOS SOUZA VILAS BOAS','zelma maria dos santos souza vilas boas','Mentoria Mãe',4,'Satisfeita mas ainda nao atinge tudo que vim buscar','Preciso de um novo onboarding com CAIO SARAIVA e VINICIUS','Tudo ok','drazelmavilasboas'),
  ('2026-08-27 15:58:25-03'::timestamptz,'Roberta Peres Vieira de Melo','roberta peres vieira de melo','Start Caio e Jordana',5,'Os mentores são muito solícitos, a didática é maravilhosa, nos deixam confiantes com a prescrição.','Gostaria de participar das aulas de gestão ao vivo.','Aulas maravilhosas e super didáticas, material de apoio excelente mas às vezes não abre no safari. Dr Caio Saraiva e dr Vinícios matravilhosos. Dr Divino é excelente em suas explicações, deixa tudo mais claro. Dra Jordana é super didático nas aulas, faz tudo parecer fácil. Dr Caio Pires além de super didático, está sempre pronto a ajudar e torna tudo simples.','@drarobertaperes'),
  ('2026-08-27 17:36:23-03'::timestamptz,'Natalia Fioramonte','natalia fioramonte','Mentoria Mãe',5,'Dedicação dos mentores em tornar a mentoria cada vez melhor e maior.','Voltar a proximidade do Caio e Vinicius na discussões dos casos.','Dr Divino está excelente!','@dranatcorte'),
  ('2026-08-27 18:26:04-03'::timestamptz,'Carolina Starling','carolina starling','Mentoria Mãe',5,'a qualidade da entrega','estou pensando mas não acho nada rs','a mentoria é maravilhosa , a entrega é total , me sinto segura para fazer prescrições hormonais e sei que vou transformar a vida da minha paciente. Só continuem sempre por favor !!! Ah só mais uma coisa : Saí da Start mas amo a Jordana e o Caio eles são maravilhosos','dra.carolinastarling'),
  ('2026-08-27 18:50:03-03'::timestamptz,'ALBINO PAIM BRANDÃO','albino paim brandao','Start Caio e Jordana',5,'Eficiência e entrega','comunicação com o setor financeiro','100%','@medinfuse_feiradesantana'),
  ('2026-08-27 20:14:56-03'::timestamptz,'Pedro Takiuti','pedro takiuti','Mentoria Mãe',5,'entrega de conteúdo','mais parte masculina','aulas muito boas, poderia ter um material para iniciantes em reposição hormonal como eu','@drpedrotakiuti'),
  ('2026-08-27 21:17:00-03'::timestamptz,'Lucas Almeida Campagnaro','lucas almeida campagnaro','Ativação',5,'Excelente entrega dos professores e todos os demais mentores','Em relação ao programa ativação: penso que poderiam disponibilizar mais aulas da plataforma e às vezes tem um preceptor pra tirar dúvidas de casos pelo WhatsApp num determinado momento, uma data específica','Excelentes professores, bom material de apoio, no entanto, acho que poderiam disponibilizar mais aulas da plataforma Endogin.','Drlucascampagnaro'),
  ('2026-08-27 21:53:00-03'::timestamptz,'Juliana Matoso Aliprandi','juliana matoso aliprandi','Mentoria Mãe',5,'A entrega','Ainda não tenho opinião formada.','Falta os slides das aulas. Gosto de imprimir e acompanhar por elas. Horários da aulas que estão difíceis de acompanhar presencial.','@drajulianaaliprandi'),
  ('2026-08-27 22:03:25-03'::timestamptz,'Andressa Samira Brunelli','andressa samira brunelli','Mentoria Mãe',3,'O motivo real é q o valor da mentoria está muito alto frente o nosso cenário econômico, e está ocorrendo mtas vendas paralelas dentro do endogin, eu esperava que ali nós já tivéssemos toda a entrega do mundo necessária. (E eles realmente entregam, mas as vendas das outras mentorias nos faz parecer que não é o suficiente)','Eu amo o endogin , acho que pra ficar mais atrativo pra nós os descontos deveriam ser melhor com as empresas parceiras (hje no mercado os preços estão quase os mesmo até pra quem não participa do endogin) . também deveríamos adaptar as estratégias de planos para o nosso cenário político atual, não podemos perder vendas peqnas, porque as vendas grandes se tornaram muito mais difíceis.','Os meninos são nota 1000. Mentoria organizada. Alinhada. Acredito que poderíamos ter mais aulas técnicas com médicos convidados tbm.','Draandressabrunelli.medica'),
  ('2026-08-27 23:24:11-03'::timestamptz,'Luisa Guimarães Castelo Branco fernandes','luisa guimaraes castelo branco fernandes','Start Caio e Jordana',4,'Eles são incríveis e indico para todos','Na parte de venda e gestão, ter um acompanhamento mais personalizado com os mentorandos, acho eles dois incríveis em técnica e conhecimento, mas sinto falta de eles nos ajudarem de fato com a prática de vender e principalmente daqueles “puxões de orelha”, da preocupação genuína com os que não estão tendo o rói e ajudar no de fato o que a gente precisa! Os conselhos sao muito gerais em relação a isso!','Ótimos','Ginecoluisacastelo'),
  ('2026-08-28 00:05:46-03'::timestamptz,'Karline Gomes Moreira Campos','karline gomes moreira campos','Mentoria Mãe',5,'A proximidade com os mentores','Tenho medo dos mentores delegarem demais as aulas e perder a essência. Qdo iniciei tinhamos mais discussões de casos e oportunidades para participar. Hj os horarios estao maus restritos.','Eu amo tudo! Sou muito grata , e gosto de todo o material disponibilizado','@drakarline.endocrino'),
  ('2026-08-28 08:00:57-03'::timestamptz,'Livia Viana Trevisan Paluan','livia viana trevisan paluan','Mentoria Mãe',5,'As pessoas que eu indiquei me agradeceram porque vale todo o investimento.','Eu não estou conseguindo acompanhar as reuniões e discussões ao vivo… acompanho o grupo de WhatsApp e assisto aulas de mentalidade gravadas. Então não consigo opinar muito. No curso da endogin percebi que muita gente estava desanimada devido a dificuldade de acesso aos meninos, mas particularmente eu não tive esse problema.','Preciso começar a revisar a plataforma. Utilizo pouco.','Draliviatrevisan'),
  ('2026-08-28 08:30:31-03'::timestamptz,'Daniel Barbosa Teixeira','daniel barbosa teixeira','Mentoria Mãe',5,'Estou muito satisfeito com a mentoria, equipe de suporte faz a diferença','Quando entrei tínhamos um pouco mais de pontos de contato com Caio e Vinicius','Tudo muito bom, realmente só tenho elogios, o ecossistema é muito bom Entendo que pelo volume de mensagens e colegas médicos nos grupos, por vezes fica realmente sobrecarregado para os meninos responder todos os casos, mas realmente gostamos do contato com eles, afinal entramos na mentoria para ter acesso a cabeça e mentalidade deles','drdanielbteixeira@gmail.com'),
  ('2026-08-28 10:12:31-03'::timestamptz,'Thaís Abreu Santos Reggiani','thais abreu santos reggiani','Start Caio e Jordana',5,'a entrega de voces.',null,null,'@drathaisabreureggiani'),
  ('2026-08-28 16:50:10-03'::timestamptz,'Regina Rebello','regina rebello','Mentoria Mãe',5,'Entrega , ambiência','Organização','Plataforma com possibilidade de ser baixada off line','drareginarebello'),
  ('2026-08-28 19:42:50-03'::timestamptz,'Alessandro Bastos','alessandro bastos','Mentoria Mãe',5,'A excelência da mentoria como um todo!','Acho que os encontros da manhã poderiam ser em horários mais ao fim do dia…','A disponibilidade dos colaboradores é significativa! Atendem a todo momento nossas dúvidas!','dralessandrobastos'),
  ('2026-08-29 13:25:29-03'::timestamptz,'Ane Caroline Barreto','ane caroline barreto','Mentoria Mãe',4,'O ambiente, s entrega dos professores','Ter mais pontos de contato, one a one, com mentores e professores. Para mês a mês trabalhar a dor pessoal. Cronograma para quem entra depois não se sentir perdido','Aulas direcionadas','draanebarreto'),
  ('2026-08-29 13:32:07-03'::timestamptz,'Carmen Maria de Araújo Lima','carmen maria de araujo lima','Mentoria Mãe',5,'Satisfação','Qdo iniciamos a dificuldade da aula no horário da manhã…. Devido Agendas já programadas','Aulas anteriores estão me ajudando muito para estimular vendas , melhorar equipe , o próprio agendamento e o principal SND','@dracarmenaraujo'),
  ('2026-08-29 13:32:23-03'::timestamptz,'Anne Karoline de Souza Torres','anne karoline de souza torres','Mentoria Mãe',5,'A entrega dos mentores, compromisso e disponibilidade deles.','Reunião individual os mentores, melhores parcerias de compras de produtos.','Plataforma excelente','@dra.annetorres'),
  ('2026-08-29 14:23:38-03'::timestamptz,'Rebeca Maria Filgueiras','rebeca maria filgueiras','Mentoria Mãe',5,'A mentoria é completa em todos os sentidos e principalmente a assistência total de Caio, Vinicius e de toda a equipe','Não tenho essa resposta agora','Até aqui estou muito impressionada positivamente com a mentoria','@dra.rebecafilgueiras'),
  ('2026-08-29 15:13:04-03'::timestamptz,'Katia Alves Ramos','katia alves ramos','Mentoria Mãe',5,'O senso de pertencimento do Ecossistema e o conhecimento e suporte dos mentores','A plataforma, pois não disponibiliza assistir em segundo plano, ne retornar de onde parou. E falta de material e slides em cada uma das aulas . Falta acesso exclusivo para o time a plataforma nas aulas do time treina time. Inclusive uma forma de incentivar os colaboradores é a emissão dos certificados para quem assisitir e participar de todas as aulas','Aulas excelentes, material de apoio pode ser disponibilizado de modo mais facil e organizado ao final de cada aula na plataforma, inclusive os slides,','@drakatia.ramos'),
  ('2026-08-29 15:24:11-03'::timestamptz,'Renata de Paula Fernandes','renata de paula fernandes','Mentoria Mãe',5,'Minha satisfação','De forma geral eu acho a mentoria incrivel. Mas as vezes fico sem resposta nos grupos. Tem q ficar insistindo ou mandando nos outros grupos.','Nada a pontuar. Estou satisfeita.','drarrnatafernandesgineco'),
  ('2026-08-29 15:44:36-03'::timestamptz,'Georgiana Oliveira da Silva Gama','georgiana oliveira da silva gama','Mentoria Mãe',5,'A entrega dos meninos!','Tornar mais claro os assuntos no site e as aulas. A entrega é tanta que chega a confundir aonde procurar e se temos aulas para os determinados assuntos.','- que Deus continue abençoando e protegendo vocês de todo mal! Vocês são seres fantásticos Caio e Vinicius! Mudaram a minha forma de atuar e sou grata demais por tê-los como meus mentores!','Drageorgianagsouza'),
  ('2026-08-29 15:50:06-03'::timestamptz,'Edmo Galvão Sodré Dourado','edmo galvao sodre dourado','Mentoria Mãe',5,'O faturamento não melhorou tanto, mas o tempo com a família melhorou muito. Também gosto muito do ambiente e ele impulsiona muito o conhecimento e uma mentalidade mais forte, isso faz toda diferença pra não desanimar.','Para os alunos que renovaram, ou seja, após fechar o ciclo de 1 ano seria muito interessante ter um onboarding individual para alinhar detalhes e até pra saber como foi de fato o ano que passou…','As aulas são boas, equipe boa, os mentores também são ótimos!','@dredmogalvao'),
  ('2026-08-29 15:58:34-03'::timestamptz,'Ana Paula Fabricio Dos Santos','ana paula fabricio dos santos','Mentoria Mãe',5,'Transformação pessoal e profissional','Colocar todas as aulas para quem quiser assistir independente dos grupos é somente os grupos podem fazer perguntas','Nota 1000 para todas as aulas professores e colaboradores','Dra Ana Paula Fabrício'),
  ('2026-08-29 16:19:55-03'::timestamptz,'HIGOR MICHEL MOREIRA CALDATO','higor michel moreira caldato','Mentores Masters',5,'SUPORTE E MOTIVAÇÃO CONSTANTE PARA NÃO DESISTIR DO PROJETO','SE POSSÍVEL, EVENTUAIS ''ONE A ONE'' PARA TROCAS PERSONALIZADAS DOS PROJETOS, COMO REALIZADA NO ONBOARDING.','TODOS EXCELENTES!','@DRHIGORCALDATO'),
  ('2026-08-29 16:23:09-03'::timestamptz,'Joao Netto','joao netto','Mentoria Mãe',5,'Participar de perto do sucesso','Nada100% 👍','Sem queixas','Instituto.drjoaonetto'),
  ('2026-08-29 17:12:32-03'::timestamptz,'Challsie Bezerra suzarte','challsie bezerra suzarte','Mentoria Mãe',4,'Acho que a parte de vendas em focar só em programa de acompanhamento deixa um pouco a desejar, porque infelizmente não é a realidade de todos. E com relação aos descontos, acho que poderia melhorar com relação aos descontos e parcerias','Vixe acima','As aulas no geral são maravilhosas, não deixa a desejar. As únicas coisas que sinto que poderia melhorar foi o que foi citado acima','Drachallsiesuzarte'),
  ('2026-08-29 17:28:07-03'::timestamptz,'Sandra h c g machado','sandra h c g machado','Mentores Masters',5,'Interesse dos mentores!','Continuar presentes para sentirmos sempre esta certeza das prescrições','Muito bom','sandragoyamachado'),
  ('2026-08-29 19:11:07-03'::timestamptz,'Elisabete Mendonça Rêgo Peixoto','elisabete mendonca rego peixoto','Mentoria Mãe',4,'Ainda sinto falta do contato mais de perto com os mentores.','Seguimentar menos a mentoria e limitar o número de alunos','Seria interessante fornecer os materiais de apoios das aulas, ebook com as condutas mais comuns e termos acesso ao artigos mais relevantes.','draelisabetemrp'),
  ('2026-08-29 19:42:28-03'::timestamptz,'henrique peres rocha','henrique peres rocha','Mentores Masters',5,'resultado / aplicação prática','Nenhum ponto que seja tão relevante, temos que nos manter atualizados e sermos os pioneiros nas novidades em nossas respectivas áreas','São excelentes','@drhenriqueperesrocha'),
  ('2026-08-29 19:55:21-03'::timestamptz,'Leonardo Pozzobon','leonardo pozzobon','Mentoria Mãe',5,'Atuação em mentalidade e conhecimento científico amplo atualizado, e sempre trazendo melhorias como Time treina Time','Atuar individualmente em gestão clínica e processos, acredito que o que distancia alguns é a capacidade de execução.','Está ótimo','@drleonardopozzobon'),
  ('2026-08-30 04:32:18-03'::timestamptz,'Cybele Cristine da Silva Costa Monteiro','cybele cristine da silva costa monteiro','Mentoria Mãe',5,'Saber que mesmo crescendo muito , a entrega dos mentores continua a mesma , até maior','Aulas de vendas','Eu amo e acho a entrega maravilhosa.','Dracybelegineco'),
  ('2026-08-30 05:47:25-03'::timestamptz,'Kamilla Kelly Moura Montenegro de Castro','kamilla kelly moura montenegro de castro','Mentoria Mãe',5,'O retorno de tudo que aprendi é muito alto. Aprendi técnica, respaldo científico, posicionamento, modelo de negócios, ter a disponibilidade deles 24h os 12 meses do ano, isso é de alto valor para mim.','Hoje eu adoraria ter alguém monitorando meu progresso na gestão, no faturamento e na aquisição de clientes. Se tivesse alguém responsável por me monitorar e que eu prestasse contas seria ótimo.','As aulas são incríveis, a disponibilidade e o carinho de Caio e Vinicius são especiais e únicos. Sobre o material e apoio sinto falta de slides para baixar em todas as aulas,','endocrinokamillamontenegro'),
  ('2026-08-30 15:04:43-03'::timestamptz,'Andrea Lopes Salzedas Tanuri','andrea lopes salzedas tanuri','Mentoria Mãe',5,'Qualidade técnica e aperfeiçoamento constante','Não sei dizer','No geral gosto de tudo, ENDOGIN evoluiu muito, só o que era melhor era com poucos alunos era mais intimista no início, mas faz parte, evoluíram muito e dão conta, acesso a eles continua excelente','draandreatanuri'),
  ('2026-08-30 19:05:54-03'::timestamptz,'Marcia da Cunha dos Reis','marcia da cunha dos reis','Mentoria Mãe',5,'Crescimento profissional. Eles te levam pela mão. Imagina eu 57 anos pensando em quanto que aprendi','Senti falta de algum encontro com os mentores para avaliar o que conseguimos e o que não conseguimos vencer','Tudo maravilhoso. Serei fã deles para sempre','dramarciacunha'),
  ('2026-08-30 22:35:32-03'::timestamptz,'VIVIAN DANIELLE BASTOS DA SILVA GONCALVES','vivian danielle bastos da silva goncalves','Mentoria Mãe',5,'pela diferença que voce-ês estão fazendo na minha vida','As vezes estranho as mudanças nas entregas de vocês, principalmente na discussão de casos, mas elas estão otimas até o momento. Outra coisa, seria possível viver um experience day com vcs? Sei que é bem difícil devido ao tamanho da mentoria, massss se houver possibilidade, eu iria amar fazer!','AS VEZES ME PERCO NA ORGANIZAÇÃO DAS AULAS NA PLATAFORMA, MAS QUANDO TENHO DUVIDA, PERGUNTO COMO ACHAR. PODIA TER UMA PASTA COM AS PRESCRIÇÕES, PDFS DAS AULAS E COM OS ARTIGOS','@DRAVIVIANBASTOS'),
  ('2026-08-31 12:00:20-03'::timestamptz,'Camila Giannecchini','camila giannecchini','Mentoria Mãe',5,'Conteudo muito rico e acesso aos mentores',null,null,'@dracamilagiannecchini'),
  ('2026-08-31 12:01:33-03'::timestamptz,'Rodrigo Alves De Medeiros Queiroz','rodrigo alves de medeiros queiroz','Mentoria Mãe',5,'Saber do comprometimento dos meninos com a ciência, verdade e boas práticas.','Organização dos eventos. Poderia ter situação de integração, para melhorar a ideia de comunidade/grupo. Além da aula, outras experiências em grupo.','No geral, estou muito satisfeito. Gostaria de uma ajuda para desbloquear o meu desafio de iniciar a colocação de implantes.','@dr.rodrigo.queiroz'),
  ('2026-08-31 12:28:41-03'::timestamptz,'Fernanda Lima Saldanha','fernanda lima saldanha','Mentoria Mãe',4,'se a procura for melhorar a parte tecnica - a nota seria 5. mas se o problema for outro, dei 4 porque sei que esta melhorando nesse aspecto de estrategias, gestao, comercial.','O medico quer atingir o que foi prometido, ter o ROI, do que foi pago. muitos conseguem de cara implementar a orientação basica de planos de acompanhamento e da super certo, porem outros nao. nesses casos precisa ter estrategias para esse medico tb. foi nesse ponto que senti falta logo que sai dos planos. nao recebi orientações para o meu caso, achei que ia melhorar, porem precisei contratar uma gestora pra me ajudar. precisa desde o inicio analisar o modelo de negocio de cada pessoa, a localização, o publico para dar as orientações direcionadas para aquele momento inicial e depois ir aprimorando. a orientação nao pode ser seca e igual para todos - saia do plano de saude, largue seu emprego publico, aumente sua consulta e implante os planos de acompanhamento.','gosto muito das aulas, materiais, porem tenho sentido falta dos mentores para responder nossos casos, que era o que eu achava muito bacana. hoje outros medicos parceiros que respondem nos grupos, nao que sejam ruim, muito pelo contrario, sao otimos tb, porem nao sao os mentores que escolhemos.','@drafernandalimafls'),
  ('2026-08-31 12:38:28-03'::timestamptz,'Amisbele Angelucci','amisbele angelucci','Mentoria Mãe',5,'A entrega de conteúdo e conhecimento é inigualável','Há apenas 30 dias na mãe, e tudo de melhor acontecendo…aulas, interação, suporte….tudo ótimo!','Tudo muito completo, aulas perfeitas, professores maravilhosos….rede de apoio do suporte sempre atentas e ajudando muito','.'),
  ('2026-08-31 12:39:03-03'::timestamptz,'Tainã Maria Durans Brito Tochetto','taina maria durans brito tochetto','Mentoria Mãe',5,'Conhecimento','Ter um olhar mais atendo para os médicos que ainda estão com faturamento baixo, não separar os braços da endogin , para quem está na endogin mãe. Como por exemplo, a mentoria de gestão, de cabelo...Seria ótimo para quem está na endogin mãe ter acesso a esses braços da endogin.','Maravilhoso, entrega excelente','@dratainatochetto'),
  ('2026-08-31 12:50:34-03'::timestamptz,'Janaína Borges da Silva','janaina borges da silva','Mentoria Mãe',5,'Excelência','Não consigo pensar em nada no momento','Os professores são excelentes, sempre acessíveis para tirar dúvidas e sempre se esforçam para trazer o máximo de conteúdo possível , evitando que fiquemos pagando mil outras mentorias a parte','Janainaborges'),
  ('2026-08-31 14:57:52-03'::timestamptz,'vitor Araujo vieira','vitor araujo vieira','Surgical',5,'qualidade da mentoria e dos mentores;','melhorar aulas de venda/gestao e onboarding com mentores serem mais constantes; adicionar as vendas a parte de rede social mesmo que básico pois nem todos da mentoria ja estao inseridos no mercado','unica coisa que senti falta foi marketing medico','@drvitor.vieira'),
  ('2026-08-31 14:58:39-03'::timestamptz,'David Bortot Raspini','david bortot raspini','Start Caio e Jordana',5,'a dedicaçao dos mentores','nao sei dizer','excelente','@drdavidraspini'),
  ('2026-08-31 15:10:31-03'::timestamptz,'Amanda Nercolini Medeiros','amanda nercolini medeiros','Ativação',5,'Professores excelentes','Não ficar individualizando tanto. Eu entendo a necessidade mas por exemplo, também é um investimento estarmos no ativação, para alguns bastante financeiramente apesar de não para outros e não temos nenhuma porcentagem de desconto em nenhuma farmácia. Coisa que outros cursos mais baratos trazem. Não precisa ser igual aos demais níveis de mentoria, mas pelo menos algo.','Plataforma muito ruim. Não aceitou meu navegador (Safari). Deveria aceitar todos.','dra.amandanmedeiros'),
  ('2026-08-31 15:27:38-03'::timestamptz,'Manoela Galvão Ramos','manoela galvao ramos','Surgical',5,'Temos um suporte muito bom dos nossos mentores','Acho que estão cada vez melhores! Abriram plantão de dúvidas .','A mentoria realmente é maravilhosa . O Caio e a Jordana são excepcionais! Como colegas e como mentores.Viraram amigos queridos As dúvidas são respondidas muito rápido! Temos um Suporte incrível. Fora isso ainda temos acesso a Mentoria mãe- Vinicius e Caio que são super acessíveis também !','Dramanoelagalvaoramos'),
  ('2026-08-31 15:45:00-03'::timestamptz,'Ingrid de Souza Lima','ingrid de souza lima','Mentoria Mãe',5,'É uma mentoria completa. Aprendemos o conteúdo, técnicas de vendas, mentalidade, espiritualidade.','A Endogin já entrega muito conteúdo e suporte de qualidade.','As aulas são didáticas e práticas, a plataforma e os os materiais são completos e os professores são maravilhosos.','draingrid.lima'),
  ('2026-08-31 19:20:26-03'::timestamptz,'Mariela Muniz','mariela muniz','Mentores Masters',5,'Tenho orientações e acompanhamento próximo','Gostaria de mais oportunidade dentro do ecossistema','Gosto das aulas , da plataforma e dos eventos','marielamunizdermato'),
  ('2026-09-01 11:43:42-03'::timestamptz,'Milene Buzzato','milene buzzato','Mentoria Mãe',5,'Desconheço mentoria mais completa q a endogin','Vcs melhoram antes da gente pensar q precisa…rs','Tudo perfeito','dramilenebuzzato'),
  ('2026-09-01 12:10:34-03'::timestamptz,'Marianny Barros Dal Col','marianny barros dal col','Start Caio e Jordana',5,'Conhecimento','Na parte de ajuda na logística do consultório','Muito boas','dramariannydalcol'),
  ('2026-09-01 12:29:16-03'::timestamptz,'Marcos Vinícius Machado Viana','marcos vinicius machado viana','Start Caio e Jordana',5,'A excelência','Ter mais aulas sobre gestão','Os meus mentores são maravilhosos!','@drviniciusm_viana'),
  ('2026-09-01 13:48:58-03'::timestamptz,'jeane Doffiny bogossian','jeane doffiny bogossian','Mentoria Mãe',5,'Pelo que a mentoria entrega , dedicação dos mentores','Gostaria de um curso de IA direcionado para médicos e um curso de gestão de clínicas mais específico','Aulas excelentes , professores ótimos . Gostaria da disponibilidade de acessar os artigos científicos na plataforma','@Dra.JeaneBogossian'),
  ('2026-09-01 19:59:02-03'::timestamptz,'Flavia Alves de Oliveira','flavia alves de oliveira','Mentoria Mãe',5,'Meu crescimento é o crescimento da minha clínica','1 tema técnico 1 x por semana a noite ajudaria na reciclagem . Fica difícil acompanhar as discursões de caso em horário comercial, Pois as vezes são disposições longas que pra Mim não ajuda . Então se tiver um dia fixo na semana à noite fica mais façil organizar . As quartas temos a cada 15 dias . Se ficar semanal pra temos usuais como recompilar masculino e feminino. Pra mim m seria ótimo','A mentoria entregou muito mais do que eu esperava . Mesmo, que o meu processo de mudança na clínica está acontecendo devagar, acho que já melhorou muito. Só tenho a agradecer .','@draflaviaalves'),
  ('2026-09-01 20:33:01-03'::timestamptz,'brenda mendonca','brenda mendonca','Mentoria Mãe',4,'Depois que os casos clinicos passaram a ter que ser em aulas, isso dificultou bastante. nao consigo entrar. e outras duas vezes entrei, mandei caso e ngm me mandou respsota do pvd.','voltar a mandar mais artigos. nao precisa mandar tudo resumido e pronto kkk mas so mandar ja é interessante para os estudos','aulas excelentes, muito conteudo, ate demais, dificil de acompanhar, mas tudo certo kk, melhor assim. professores otimos.','drabrendamendonca'),
  ('2026-09-01 21:10:43-03'::timestamptz,'Márcia Verônica Paes Fonsêca','marcia veronica paes fonseca','Mentoria Mãe',5,'É um curso riquíssimo em informação tecnica, discussão de casos clínicos, o comprometimento de Caio e Vinicius com o crescimento dos mentorandos é incrível, a energia e generosidade, idem.','Talvez a apresentação do método em material de pdf, para consultar de forma rapida qdo fossemos decidir os nossos implantes.','Acho que poderia estar mais claro o material de apoio, como falei antes. Às vezes, quero lembrar de algo que ouvi na aula, mas não localizo facilmente a informação ouvindo os videos.','@dramarciafonseca'),
  ('2026-09-01 21:14:30-03'::timestamptz,'Begona Garcia Wicks','begona garcia wicks','Mentoria Mãe',5,'O conteúdo apresentado e os resultados.','Separar na plataforma as aulas por assunto e ter algum tipo de material escrito para poder fazer uma leitura mais dinâmica. Muitas vezes reler um assunto facilita a compreensão.','Acho tudo muito bem organizado, mas sinto falta de material de apoio, como ter algum acesso rápido ao estudos e artigos citados .','@begwicks'),
  ('2026-09-01 21:33:28-03'::timestamptz,'Paulo Abreu Neto','paulo abreu neto','Mentoria Mãe',5,'Entrega dos mentores','Mais on board no meio do ciclo , pois em alguns momentos nós mesmos relaxamos no processo e o on board nos traz p jogo','Sensacional','@drpauloabreu'),
  ('2026-09-01 22:33:25-03'::timestamptz,'Ana Valéria Ramirez','ana valeria ramirez','Mentoria Mãe',5,'Estou muito satisfeita','Está excelente a mentoria','Adoro estar na Endogyn mãe','Dra.anavalerianutrologa'),
  ('2026-09-01 22:52:15-03'::timestamptz,'Silvana Guedes Gomes','silvana guedes gomes','Mentoria Mãe',5,'A atenção dos mentores a a preocupação genuína deles com os mentorados','Discussão de casos clínicos serem mais objetivas. bate papo demais. Acho que tem gente que as vezes fala demais e os casos não fluem.','Aulas excelentes. Amo nossos professores','@drasilvanaguedes'),
  ('2026-09-01 23:22:46-03'::timestamptz,'MATHEUS LEMOS','matheus lemos','Mentoria Mãe',5,'Muita entrega de conhecimento técnico, ambiente que respira mentalidade/espiritualidade afiadas, nossos mentores e colegas como referencia alta, e constância para manter engajado no propósito!!','A parte de gestão: como estruturar processos comerciais, operacionais, contábeis.','Plataforma riquíssima com muito conteúdo e de ótima qualidade, porem difícil procurar alguma aula especifica, muitas reuniões importantes sem títulos. Poderiam fazer um itinerário sobre o que temos de aulas a serem estudadas.','drmatheuslemos'),
  ('2026-09-01 23:32:22-03'::timestamptz,'Luiz Guilherme De Campos Ribeiro Filho','luiz guilherme de campos ribeiro filho','Mentoria Mãe',5,'Enxergo o potencial','Acho que a plataforma de vídeos poderia estar melhor organizada. Casos clínicos organizados por tema, em vídeos mais curto. Acredito que o trabalho para organizar valeria a pena, pois fica mais fácil encontrar situações semelhantes que podemos enfrentar, e tirar as dúvidas ali mesmo, fazer associações, comparações. Etc.','É um time ímpar totalmente capacitado e didático. Material prático e sem rodeios.','@dr.luizdecampos'),
  ('2026-09-03 06:02:23-03'::timestamptz,'Igor de Brito silva Alves','igor de brito silva alves','Mentoria Mãe',5,'Mudou minha vida','Não vejo como','Aulas fenomenais , network espetacular, ambiente de crescimento e eventos cada vez melhores','@dr.igoralves'),
  ('2026-09-03 14:22:59-03'::timestamptz,'Tércia Tarciane Soares de Sousa','tercia tarciane soares de sousa','Start Caio e Jordana',5,'Entrega de tudo é excelente','Por ora ainda não tenho algo especifico para pontuar.','Excelente!','@dra.terciasousa'),
  ('2026-09-04 15:57:42-03'::timestamptz,'Frederico Chaves','frederico chaves','Start Caio e Jordana',5,'Organização/ mentalidade/ entrega','Montar cronograma dos encontros de forma mensal, para podermos nos organizar. Capacitação em implantes devia ser inclusa no valor da mentoria','Tudo muito bom até o momento','drfredericochaves'),
  ('2026-09-06 17:04:54-03'::timestamptz,'Bruno Landim','bruno landim','Mentoria Mãe',5,'Estou gostando da entrega','Abrir o neurogin para ajudar os colegas a resolverem casos bem difíceis através da terapia neural','Excelente a entrega','@drbruno Landim'),
  ('2026-09-06 20:40:33-03'::timestamptz,'Roberta Carlesso Miele','roberta carlesso miele','Mentoria Mãe',5,'A mentoria está bem abrangente e apesar de ter muitos mentorados Vinicius e Caio seguem próximos ( o que muito valorizo).','Pegar + na mao ou dar + chinelada do mentorado ( no caso eu) quando está estagnado, eu gostaria.','Na plataforma nao esta tao facil de localizar as aulas e ainda tenho dificuldade app da MLS','@dra.robertamiele'),
  ('2026-09-06 22:36:01-03'::timestamptz,'Cristiane de Paiva Silveira Aguiar','cristiane de paiva silveira aguiar','Mentoria Mãe',5,'Estar muito satisfeita nesse ecossistema','Organizar melhor a nossa plataforma para a busca das aulas por temas','Eu adoro fazer parte dessa mentoria e não pretendo sair daqui NUNCA ! Muito grata !','@dra_cristianeaguiar_'),
  ('2026-09-08 08:05:22-03'::timestamptz,'Bruno Moura','bruno moura','Mentoria Mãe',5,'Satisfação e proximidade dos mentores','Estar com mentores mais próximos e entregas pessoais com os mentores','Cuidado ao não delegar tantas atividades a terceiros, afinal “compramos” estar com os mentores','@dr.bmoura'),
  ('2026-09-08 16:21:39-03'::timestamptz,'Eline de Almeida Soriano','eline de almeida soriano','Mentoria Mãe',3,'Não ter conseguido aumentar o faturamento','Menos grupos, isso deixa a pessoa meio confusa e sem conseguir acompanhar','Gosto muito dos professores','dra.elinesoriano@gmail.com'),
  ('2026-09-08 20:52:16-03'::timestamptz,'Mayara Bega Freitas Veloza','mayara bega freitas veloza','Mentoria Mãe',5,'Confiança no caráter e na verdade que os mentores carregam','Mais suporte para dúvidas. Ser algo mais direcionado sem tanta conversa paralela para poder agilizar.','Aulas são fantásticas. Destaque para o Divino que é super detalhista, eu adoro isso. Poderia ter uma organização melhor na plataforma dos temas. Mais conteúdos pirulas porque agiliza o aprendizado. Fazer um destaque dos principais pontos da aula, coisas que tem que saber.','@mayveloza'),
  ('2026-09-08 21:16:06-03'::timestamptz,'Bruna frança','bruna franca','Mentoria Mãe',5,'Assistência dos mentores','Falar mais sobre casos que não deram certo na vida real , citar complicações de pacientes, casos difíceis e tb contra indicações . Acabo ficando receosa de só ouvir o lado bom dos hormônios por aqui.','A mentoria eh extraordinária . Caio e Vinícius são meninos extremamente humanos e inteligentes . Sou grata demais aos dois!','Dra Bruna.franca'),
  ('2026-09-09 06:52:42-03'::timestamptz,'Erika Jacob','erika jacob','Mentoria Mãe',5,'Ajudar muito na mentalidade.','Ensinar a liderar melhor. Delegar, dividir funções de cada um, aprender a contratar, aprender a “mandar”, corrigir, ensinar de forma correta, treinar… organizar melhor o tempo e despender energia nas coisas certas.','Tudo dentro dos conformes. Ajustando agenda e horários para acompanhar melhor as aulas e tirar dúvidas. Ainda estou no início e adaptando. Podia tb ter algo sobre liderança.','@draerikajacob'),
  ('2026-09-09 08:05:57-03'::timestamptz,'Cristinne Breval Teixeira','cristinne breval teixeira','Mentoria Mãe',5,'Eu me tornei fã','No meu caso seria muito importante um estágio em uma clínica grande , pra ver como eles fazem fechamento o andamento da consulta acho que dessa forma eu conseguiria melhorar na minha parte de vendas','Nível técnico dessa aulas é altíssima, os meninos são incensáveis,','@draxrisbreval'),
  ('2026-09-09 09:14:58-03'::timestamptz,'Djeime da Rocha Benfica Ribeiro','djeime da rocha benfica ribeiro','Start Caio e Jordana',5,'Entregáveis','Estou satisfeita com entrega atual',null,'dradjeime'),
  ('2026-09-09 09:24:56-03'::timestamptz,'DrJosé manoel De souza','drjose manoel de souza','Start Caio e Jordana',5,'O material, o acompanhamento dos mentores','Mais práticas','Ótimas aulas','dr.josemanoel'),
  ('2026-09-09 09:41:08-03'::timestamptz,'raimundo vitoriano correia neto','raimundo vitoriano correia neto','Start Caio e Jordana',5,'PORQUE É EFICAZ','O CONTEUDO DA PLATAFORMA, ELA É MUITO DESORGANIZADA , MUITO CHATO AS AULAS IMPORTANTES SEREM AULAS DE EVENTOS , PRECISAMOS DE UMA PLATAFORMA MAIS OBJETIVA COM AULAS MAIS OBJETIVAS. ISSO NECESSITA MUDAR MUITO','AS AULAS AO VIVO QUANDO PARTICIPAMOS SÃO ÓTIMAS AS GRAVADAS SÃO PÉSSIMAS , PERDEMOS MUITO TEMPO COM COISAS QUE NÃO ESTÃO NO CONTEXTO .','vitoriano_neto e dr.vitorianoneto'),
  ('2026-09-09 10:03:25-03'::timestamptz,'Felipe de Paula Andrade','felipe de paula andrade','Start Caio e Jordana',3,'Ainda n consegui os resultados que esperava. Espero que seja pq tem apenas 2 meses.','Estratégias para que o médico endogin na medida do possível consiga resolver todos os problemas do paciente. Gostaria de se possível aprender colocação de DIU. Interação mais próxima e facilitada aos mentores, indo além da parte clínica, como exemplo buscando entender e intervir na realidade individual da clínica do mentorando. Acho q isso será solucionado com o treinamento da equipe,','Aulas excelentes. Sinto falta dos PDFs das aulas.','@dr.felipedepaulaandrade'),
  ('2026-09-09 10:25:38-03'::timestamptz,'JIMI SCARPARO','jimi scarparo','Surgical',5,'Seriedade de entrega - conhecimento dos mentores - espiritualidade e mentalidade de crescimento e escala - parcerias','1. Trancar o áudio de todas as pessoas durante as aulas 2. Criar um sistema de prescrição on Line endogin com protocolos sugeridos para cada caso (os mais comuns pelo menos) 3. Chamar palestrantes em vendas e marketing nas aulas de terça de manhã 4. Criar mais parcerias com outros fornecedores','É notável o crescimento da endogin em tão pouco tempo. Isso se dá pela seriedade com que Caio e Vinícius encaram sua responsabilidade com o ecossistema. A proximidade com os mentores e a acessibilidade me conquistaram. Tenho o número pessoal dos dois e toda vez que precisei de ajuda eles se prontificaram. Continuem assim!','@dr.jimiscarparo'),
  ('2026-09-09 10:26:08-03'::timestamptz,'Raphael Torres Figueiredo de Lucena','raphael torres figueiredo de lucena','Surgical',5,'Comprometimento da equipe','Ter mais contato com Caio Saraiva e Vinicius','Aulas e professores são muito bons','Dr.raphaellucena'),
  ('2026-09-09 10:35:30-03'::timestamptz,'Mateus Facchjn','mateus facchjn','Start Caio e Jordana',5,'Entrega','Discussão de casos em canal com algum tutor específico direto sem deixar no grupo .','Muito bom','dr.mateusfacchin'),
  ('2026-09-09 13:31:10-03'::timestamptz,'Cinthia Albuquerque Feijó','cinthia albuquerque feijo','Start Caio e Jordana',5,'Satisfação','Seria interessante acompanhar mais de perto cada mentorando com reunião particular mensal','Sem queixas.','@dra.cinthiafeijo'),
  ('2026-09-09 13:31:48-03'::timestamptz,'Alice Zanella','alice zanella','Start Caio e Jordana',5,'Caio e jornada são ótimos no suporte','Tudo certo','Bom suporte e material Sem nenhuma reclamação','@zanellaalice_'),
  ('2026-09-09 16:48:11-03'::timestamptz,'Vilson Maciel','vilson maciel','Ativação',4,'Nunca somls Perfeitos e procuramos sempre atingir a perfeição','Participei do Endogin 1 e agora fiz o 3, acredito que muitas pessoas como foi este ultimo, perde um pouco do contato! As aulas foram otimas, mas o excesso de pessoas, tumultua .','Penso que oportunidade que estamos tendo no tira duvidas com Caio, Jordana, Twoany, Regina e Divino, tem sido excelente e talvez uma plataforma voltada para isso seria importante para quem ja esta na rotina a muitos anos! Pena que será limitado e se tivéssemos a oportunidade de adquirir somente esta modalidade, seria importante','@vilson.ginecologista'),
  ('2026-09-09 18:24:27-03'::timestamptz,'Alicia Christiane Imada de Oliveira','alicia christiane imada de oliveira','Ativação',5,'O curso é o mais completo, já tinha comprado os cursos do Diogo Viana que são bons, mas nada se iguala a metodologia da endogin','Descontos de produtos para endogin ativação','Como estou tendo dificuldade de captação de pacientes, gostaria de algo mais nesse sentindo','Draaliciaimada'),
  ('2026-09-10 05:24:06-03'::timestamptz,'Daniele Aragão de Albuquerque','daniele aragao de albuquerque','Start Caio e Jordana',5,'Profissionais maravilhosos','Material por escrito pra gente imprimir já com os protocolos pra aplicar também. A gente precisa tá assistindo a aula e anotando e as vezes a gente esquece e não sabe qual aula foi.','Parabenizar a mentoria. Pra mim é a melhor das mentorias que faço. Porém muita coisa não consegui colocar em prática porque ainda estou muito conhecida como obstetra na minha cidade.','DraDanieleaaragao'),
  ('2026-09-11 14:37:31-03'::timestamptz,'Layza Luyza de Andrade Belo','layza luyza de andrade belo','Start Caio e Jordana',5,'Aprendizado Admiração Empenho','Gostaria de aprender mais sobre captação e vendas, além de treinar minha atendente (acho o principal ponto).','Somente agradecer toda minha mudança de mentalidade. Me mostrar que trabalhar não é trabalho. Passar a amar o que faço ao invés de ver meu trabalho apenas como fonte de renda. Aos meus mentores, que Deus continue aos abençoar e abrir caminho inimagináveis na vida de cada um deles.','Dralayzabelo'),
  ('2026-09-12 06:53:34-03'::timestamptz,'Andrea Perfeito','andrea perfeito','Mentoria Mãe',5,'Alta entrega e comprometimento com nossas necessidades','Colocar mais treinamento com nosso time : vendas , enfermagem , gestão','Material de excelente qualidade , professores didáticos e cordiais e equipe de apoio as CS MARAVILHOSAS','Draandreaperfeito'),
  ('2026-09-13 10:43:48-03'::timestamptz,'Sinara maria de castro','sinara maria de castro','Ativação',5,'Por tudo que já disse','.','.','Drasinara_castro'),
  ('2026-09-14 10:26:46-03'::timestamptz,'Blima De Rossi','blima de rossi','Start Caio e Jordana',5,'Gosto muito da estrutura e todo o suporte. Inclusive minhas amigas médicas mais próximas também já estão na mentoria.','Acredito que já estão melhorando o que eu sentia falta. Parte de gestão, marketing, treinamento de time - são areas que tenho mais dificuldade.','Só tenho elogios a fazer. Aulas com conteúdo simples, atualizado e muito prático. Suporte do Caio e da Jordana todas as vezes que precisei por mais simples que fosse minha duvida. Muita segurança para passar os tratamentos para os pacientes.','@drablimaderossi'),
  ('2026-09-14 11:32:04-03'::timestamptz,'Lívia paula Vasconcelos Gouveia','livia paula vasconcelos gouveia','Start Caio e Jordana',5,'O que oferece e tudo que aprendemos','Difícil, mas eu gostaria que tivesse on board de tempos em tempos hahahah','A entrega em tudo o que vocês fazem é sensacional!!','@dra.liviaapvasconcelos'),
  ('2026-09-14 11:33:43-03'::timestamptz,'Luiz Fernando Cabral Rezende','luiz fernando cabral rezende','Start Caio e Jordana',5,'Entrega completa da mentoria','Mais aulas técnicas','Nota mil','dr.luizfernando_cr'),
  ('2026-09-14 11:36:24-03'::timestamptz,'Giorgio Baretta','giorgio baretta','Surgical',5,'Satisfeito','Mais hands on e visitas a clinicas dos mentores e qualificadas','100%','@drgiorgiobaretta'),
  ('2026-09-14 17:23:43-03'::timestamptz,'Edmo Galvão Sodré Dourado','edmo galvao sodre dourado','Mentoria Mãe',5,'Gosto muito da entrega dos mentores','Gostaria muito que tivesse novo on boarding individual após renovação, está próximo de forma mais individual com os mentores trás mais energia.','.','Dredmogalvao'),
  ('2026-09-14 18:33:38-03'::timestamptz,'Gabriela Becker','gabriela becker','Mentoria Mãe',5,'Entregam muito conteúdo','Mais encontros presenciais','Apenas na plataforma que poderia ser dividido por ordem de datas, as vezes quando entramos ficamos um pouco perdidos com excesso de aulas na plataforma Hehe','Dragabrielabecker'),
  ('2026-09-15 07:47:08-03'::timestamptz,'Cibele Lemos Lacerda','cibele lemos lacerda','Start Caio e Jordana',5,'Muito apoio teórico e individual','Poderíamos ter mais de um grupo no WhatsApp. Vejo que estão crescendo muito a quantidade de alunos e muitos já perguntam sem ter visto nenhuma aula','Tenho dificuldade de encontrar as aulas na plataforma. Um esquema, resumo co Os pontos mais importantes de cada aula. Resumo','dracibelelemos'),
  ('2026-09-15 09:47:08-03'::timestamptz,'Jullianny Scarparo','jullianny scarparo','Surgical',5,'Entrega','Mais eventos presenciais','Excelente - Caio e Jordana são super prestativos','@drajuscarparo'),
  ('2026-09-16 11:07:27-03'::timestamptz,'Roberto cesar leite','roberto cesar leite','Endogin Scale',5,'Conteúdo','Nada','Ótimo','Não'),
  ('2026-09-16 14:54:02-03'::timestamptz,'Jullianny Scarparo','jullianny scarparo','Surgical',5,'Excelência médica, transparência, acolhimento, visão…','Na última quarta, 09/09, assisti uma aula do Caio Saraiva, gostei muito deste perfil de aula. Talvez, se tivéssemos 1x/mes, seria ótima opção','Estou satisfeita com o que tenho recebido','Drajuscarparo'),
  ('2026-09-16 18:33:58-03'::timestamptz,'Nissrin Antar Mohammed','nissrin antar mohammed','Start Caio e Jordana',5,'Melhorei em técnica, mentalidade, a mentoria me trouxe muitos ganhos','Gostaria de mais conteúdos sobre gestão','Caio, Jordana, Caio e Mamede são sensacionais, todos. Estou muito satisfeitas com os mentores, principalmente Caio e jordana q são muito acessíveis','@dranissrinantar'),
  ('2026-09-16 20:39:46-03'::timestamptz,'Michele Martins Ferraz','michele martins ferraz','Start Caio e Jordana',4,'O fato de dar ROI','Ter onboarding individual de forma periódica para traçar metas de acordo com o momento que cada um está vivendo','As aulas e os materiais são excelentes, assim como os professores, que são muito solícitos. Nesse aspecto, realmente não tenho nada do que reclamar.','@dramicheleferraz'),
  ('2026-09-17 10:58:45-03'::timestamptz,'Eduardo Jorge','eduardo jorge','Start Caio e Jordana',5,'Tudo de bom que tenho aprendido com a mentoria','Nunca mudem.','Agradecer muito a Jordana e Caio por todo o suporte e ajuda.. eles tem sido excelente mentores. Me ajudando muito a crescer como pessoa e profissional. Agradecer muito ao Caio e Vinícius, nunca pensei em entrar em uma mentoria, ainda bem que fui no curso endogin e me deslumbrei com tanto conhecimento e ambiente para crescimento.','@dreduardojorge'),
  ('2026-09-18 12:16:24-03'::timestamptz,'Maria Gertrudes Ouriques Teles','maria gertrudes ouriques teles','Ativação',5,'TUDO','Eh um Volume grande de informação. As vezes recebemos informações sobre aulas em cima da hora . O Som Do Vinicius, sempre não eh tão bom, não sei o porquê. Rsrs','Acho que o referido na resposta anterior . Com o tempo vou sentindo mais um Pouco . Muito Obrigada, feliz em está com vcs . Gertrudes Ouriques','@gertrudesouriques'),
  ('2026-09-20 10:43:25-03'::timestamptz,'Daniela Jobst','daniela jobst','Mentoria Mãe',4,'Falta gestao para as clinicas de forma individual , personalização do seu negocio , comercial.','Ajudar nas estruturações comercias, gestao do seu negocio de modelo, atuar com a minha equipe e me ensinar a gerir.','Aulas, conteúdo excelentes','dradanielajobst'),
  ('2026-09-20 12:03:45-03'::timestamptz,'Kamilla Montenegro','kamilla montenegro','Mentoria Mãe',5,'Entrega total, qualidade dos materiais, cuidado dos mentores Caio e Vinicius sempre prontos a me ajudar.','Na parte de gestão mesmo, para preparar nossas clínicas a executar os processos treinando a equipe, supervisando as vendas e o faturamento um a um. Será um braço muito importante.','Aulas excelentes, materiais claros e atualizados, disponibilidade dos mentores total, isso é fundamental e único. Atualizações diárias no grupo de informes Endogin com as interpretações e conselhos do Caio. Só gratidão. Ah, se pudesse melhorar algo, seria ter slide para todas as aulas, nem todas tem.','@endocrinokamillamontenegro'),
  ('2026-09-21 14:24:18-03'::timestamptz,'Renan alves garcia','renan alves garcia','Start Caio e Jordana',5,'Qualidade da mentoria','Não tem.','Todos professores excelentes.','@drrenan.garcia'),
  ('2026-09-22 09:35:05-03'::timestamptz,'Mateus Louis Rodrigues Cavalcante','mateus louis rodrigues cavalcante','Start Regina e Twoany',3,'Valor','Poderia ter mais tutores, sinto falta do início quando era mais próximo a mentoria','São muito boas!','Drmateus.cavalcante'),
  ('2026-09-22 09:36:36-03'::timestamptz,'Fernanda de Castro Roque','fernanda de castro roque','Start Regina e Twoany',5,'Entrega completa','Melhorar organização de aulas. No início da semana aparece uma agenda e no decorrer da semana surgem aulas aleatórias que não estavam na programação. Acabo não conseguindo acompanhar.','Material completo, aulas com entrega incrível e professores muito atualizados','@drafernandaroque'),
  ('2026-09-22 10:09:48-03'::timestamptz,'Ana carolina Abreu','ana carolina abreu','Start Regina e Twoany',5,'Muito aprendizado técnico','Ajuda com os bastidores da clinica','Aulas muito boas, volume de aula, acesso, material, tudo excelente. Gestão atualmente é meu maior desafio','@dranacarolina'),
  ('2026-09-22 11:18:21-03'::timestamptz,'Ende Tâned Barroso Barros Amorim','ende taned barroso barros amorim','Start Caio e Jordana',5,'Pelos conteúdos e pela dedicação dos meus mentores que estão sempre disponíveis.','Um acompanhamento um pouco mais individual','Amo ser endogin','@institutoendeamorim'),
  ('2026-09-22 12:01:24-03'::timestamptz,'Vanessa Rocha Pessoa','vanessa rocha pessoa','Start Caio e Jordana',5,'Satisfação em toda equipe da Endogin , sou apaixonada .','Para mim está muito perfeito . Todos os mentores sempre já chegam com inovação .','Aulas e material perfeitos','dravanessapessoa'),
  ('2026-09-22 13:21:51-03'::timestamptz,'Romolo guida','romolo guida','Start Caio e Jordana',5,'E entrega','Vcs já estão fazendo isso, colocando o autora mentorados para dividir as experiências de sucesso','Hoje todos tratamos homens e mulheres mas o foco ainda está muito em mulheres. O básico do homem não está bem descrito . Outra coisa são as patologias associadas, dislipidemia , hipogonadismo … tudo isso influencia e muito no emagrecimento . Isso não é nem citado !','romologuidaurologia'),
  ('2026-09-22 20:43:57-03'::timestamptz,'Cybelle Bertoldo','cybelle bertoldo','Start Regina e Twoany',5,'A Endogin entrega muito mais do que eu esperava e cumpriu o que as mentoras me disseram no Onboarding "A Endogin se paga"','Já fazia inserção de implantes absorvíveis antes de entrar na Endogin. Aqui aprimorei meu conhecimento mas senti falta de um vídeo prático de como inserir o silástico. Infelizmente tive um acidente de carro e não poderei participar do Hands On pq é o preço da franquia do seguro do meu carro. Acredito que um vídeo já seria suficiente para q eu destravasse a ideia de prescrever e implantar silastico.','Somente elogios aos mentores e aulas sensacionais!','@dracybellebertoldo'),
  ('2026-09-22 21:35:49-03'::timestamptz,'Fabiana Almeida','fabiana almeida','Start Caio e Jordana',5,'A entrega da Jordana e do Caio é surreal','Ter mais prática na inserção do implante','Equipe maravilhosa! Dr Caio e dra Jordana estão sempre prontos e dispostos a nos ajudar, tirar dúvidas, eles realmente nos guiam por toda a trajetória','@dra.fabiana_miranda');

-- casa com o aluno pelo nome (o formulário não pede e-mail)
alter table pesquisa_nps add column student_id uuid;
update pesquisa_nps p set student_id = s.id
  from students s
 where lower(regexp_replace(translate(s.full_name,
        'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
        'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC'), '[^A-Za-z ]', ' ', 'g')) ~ ('^' || p.chave || '$')
    or lower(regexp_replace(translate(s.full_name,
        'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
        'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC'), '[^A-Za-z ]', ' ', 'g')) = p.chave;

-- RELATÓRIO (não muda nada): quantas casaram
select count(*) as respostas,
       count(student_id) as casaram_com_aluno,
       count(*) - count(student_id) as sem_aluno_encontrado
  from pesquisa_nps;

select nome, mentoria, nota from pesquisa_nps where student_id is null order by nome;

-- IMPORTA (não duplica: apaga antes o que já tiver vindo desta pesquisa)
delete from nps_responses where source = 'pesquisa_2026_08';

insert into nps_responses (student_id, score, score_raw, scale, comment, source,
                           respondent_name, mentoria_informada, motivo, melhorar,
                           feedback_geral, instagram, created_at)
select p.student_id,
       round(p.nota * 2.0)::int,   -- 0-5 → 0-10
       p.nota, 5,
       coalesce(p.motivo, p.feedback_geral),
       'pesquisa_2026_08',
       p.nome, p.mentoria, p.motivo, p.melhorar, p.feedback_geral, p.instagram,
       p.respondido_em
  from pesquisa_nps p;

notify pgrst, 'reload schema';

select count(*) as importadas,
       round(avg(score_raw)::numeric, 2) as nota_media_0a5,
       count(*) filter (where score_raw = 5) as notas_5
  from nps_responses where source = 'pesquisa_2026_08';
