-- v63: acerta o STATUS de cada aluno com a planilha da Thaís.
--
-- O que eu errei no v60: a planilha marca "Ativo" também em quem está
-- TRANCADO (uma coluna à parte) e em quem está "Resolvendo". Eu joguei os
-- três no mesmo balaio 'ativo'. A conta certa da planilha é:
--   423 ativos · 12 trancados · 12 resolvendo · 18 encerraram = 465
--
-- Aqui: trancado vira status 'trancado'; resolvendo fica 'ativo' com a
-- situação anotada na renovação (é aluno ativo em tratativa); encerrou fica
-- 'cancelado' e escondido da diretoria.

drop table if exists status_planilha;
create table status_planilha (email text primary key, status_real text, rotulo text);
insert into status_planilha (email, status_real, rotulo) values
  ('luanacb@icloud.com','ativo','Ativo'),
  ('zanella.alice@gmail.com','ativo','Ativo'),
  ('anarobertaandrada@hotmail.com','ativo','Ativo'),
  ('aandressadepaula@gmail.com','ativo','Ativo'),
  ('augustofavaleite@gmail.com','ativo','Ativo'),
  ('biancacdamin@gmail.com','ativo','Ativo'),
  ('drablimaderossi@hotmail.com','ativo','Ativo'),
  ('bruhandressa23@icloud.com','ativo','Ativo'),
  ('drabrunahering@gmail.com','ativo','Ativo'),
  ('bruno.aguila87@gmail.com','ativo','Ativo'),
  ('cami_gava@hotmail.com','ativo','Ativo'),
  ('ctplacerda@outlook.com','ativo','Ativo'),
  ('chrisfalci@hotmail.com','ativo','Ativo'),
  ('cibele-lemos@hotmail.com','ativo','Ativo'),
  ('dania.albuquerque@gmail.com','ativo','Ativo'),
  ('raspini@hotmail.com','ativo','Ativo'),
  ('eduardojorge@oncoginecologia.com.br','ativo','Ativo'),
  ('endetaned@outlook.com','ativo','Ativo'),
  ('fabianamiranda793@gmail.com','ativo','Ativo'),
  ('moraesfernandap@gmail.com','cancelado','Encerrou Mentoria'),
  ('gisaffonseca@hotmail.com','ativo','Ativo'),
  ('glauco.piassi@hotmail.com','ativo','Ativo'),
  ('isabellaccarvalho_@outlook.com','ativo','Ativo'),
  ('draisabellacunha@gmail.com','ativo','Ativo'),
  ('isadora.angelicola@gmail.com','ativo','Ativo'),
  ('joaofon2912@gmail.com','ativo','Ativo'),
  ('drsouzajrkef@gmail.com','ativo','Ativo'),
  ('karinerantunes@hotmail.com','ativo','Ativo'),
  ('karolinemcosta@yahoo.com.br','ativo','Ativo'),
  ('layzaandrade_84@hotmail.com','ativo','Ativo'),
  ('neto_bz@hotmail.com','ativo','Ativo'),
  ('liviaapvasconcelos@gmail.com','ativo','Ativo'),
  ('lucymaria-bdc@hotmail.com','ativo','Ativo'),
  ('luisacastelob2@hotmail.com','ativo','Ativo'),
  ('luizfernandocabralrezende@hotmail.com','ativo','Ativo'),
  ('marvis.mv@gmail.com','ativo','Ativo'),
  ('mbdalcol@hotmail.com','ativo','Ativo'),
  ('drmateusfacchin@gmail.com','ativo','Ativo'),
  ('micheleferraz87@gmail.com','ativo','Ativo'),
  ('nis_mohammed@hotmail.com','ativo','Ativo'),
  ('normanagime@yahoo.com.br','ativo','Ativo'),
  ('vitorianoneto@gmail.com','ativo','Ativo'),
  ('drrenanagarcia@gmail.com','ativo','Ativo'),
  ('robertapvm@gmail.com','ativo','Ativo'),
  ('romolo.guida@gmail.com','ativo','Ativo'),
  ('sfcentermed@gmail.com','ativo','Ativo'),
  ('sohailadalbianco@gmail.com','ativo','Ativo'),
  ('suzanasralves@gmail.com','ativo','Ativo'),
  ('dratatianenacif@gmail.com','ativo','Ativo'),
  ('thaismnzs@yahoo.com.br','ativo','Ativo'),
  ('drathaisabramusse@gmail.com','ativo','Ativo'),
  ('vanessalbrandao@gmail.com','ativo','Ativo'),
  ('vanrochapessoa@hotmail.com','ativo','Ativo'),
  ('wendel.petrucio@gmail.com','cancelado','Encerrou Mentoria'),
  ('felipe_dipaula.a@hotmail.com','ativo','Ativo'),
  ('dra.terciasousa.med@gmail.com/tercia_tarciane@hotmail.com','ativo','Ativo'),
  ('mmunizspadini@gmail.com','ativo','Ativo'),
  ('aj_motta@hotmail.com','ativo','Ativo'),
  ('contato@sincrovida.com.br','ativo','Ativo'),
  ('dradjeime@gmail.com','ativo','Ativo'),
  ('ronaldomorari@gmail.com','ativo','Ativo'),
  ('scheilasilva@yahoo.com.br','ativo','Ativo'),
  ('albinopaim4@outlook.com','ativo','Ativo'),
  ('tascila74@gmail.com','ativo','Ativo'),
  ('thaisabreureggiani@gmail.com','ativo','Ativo'),
  ('ketlimpriscilla@hotmail.com','ativo','Ativo'),
  ('c-juliani@hotmail.com','ativo','Ativo'),
  ('cantarelli@cmdiagnostica.com.br','ativo','Ativo'),
  ('esther-amorim@hotmail.com','ativo','Ativo'),
  ('dr.fredericofchaves@gmail.com','ativo','Ativo'),
  ('drakarinakakizaki@gmail.com','ativo','Ativo'),
  ('nayaracibelly@gmail.com','ativo','Ativo'),
  ('dramarcelabrasil@hotmail.com','ativo','Ativo'),
  ('isarampazzo@me.com','ativo','Ativo'),
  ('savionobree@hotmail.com','ativo','Ativo'),
  ('ramos.almino@gmail.com','ativo','Ativo'),
  ('drbrunormota@bol.com.br','ativo','Ativo'),
  ('cinthiafeijo@hotmail.com','ativo','Ativo'),
  ('claudio.pe91@gmail.com','ativo','Ativo'),
  ('edgof@yahoo.com.br','ativo','Ativo'),
  ('gerlianom@gmail.com','ativo','Ativo'),
  ('giorgio.baretta@gmail.com','ativo','Ativo'),
  ('drgustavocoimbra@gmail.com','ativo','Ativo'),
  ('faturamento@gastro-centro.com / jnicareta@uol.com.br//jnicareta@gmail.com','ativo','Ativo'),
  ('drjimi@scarparoscopia.com','ativo','Ativo'),
  ('drvaladaoslz@gmail.com','ativo','Ativo'),
  ('jully.scarparo@gmail.com','ativo','Ativo'),
  ('drlucasrossi@gmail.com','ativo','Ativo'),
  ('lslucianasiqueira@gmail.com','cancelado','Encerrou Mentoria'),
  ('galvao.manoela@gmail.com','ativo','Ativo'),
  ('marcioschenato@gmail.com','ativo','Ativo'),
  ('mayaramasilva@hotmail.com//dramayaramagry@gmail.com','ativo','Ativo'),
  ('paulovblima@gmail.com','cancelado','Encerrou Mentoria'),
  ('raphael_torres@hotmail.com','ativo','Ativo'),
  ('ttsbrasil@gmail.com','ativo','Ativo'),
  ('vieira.vitor1@gmail.com','ativo','Ativo'),
  ('andreiakataiama@gmail.com','ativo','Ativo'),
  ('talytasv@gmail.com','ativo','Ativo'),
  ('alessandracmiranda@icloud.com','ativo','Ativo'),
  ('dramanda.go@hotmail.com','ativo','Ativo'),
  ('amanda_aarao@yahoo.com.br','ativo','Ativo'),
  ('aninhaabt@yahoo.com.br','ativo','Ativo'),
  ('bumlima@hotmail.com','ativo','Ativo'),
  ('camilecardosoo@gmail.com','ativo','Ativo'),
  ('carolcassabgenaro@hotmail.com','ativo','Ativo'),
  ('carolfariamiurim@hotmail.com','ativo','Ativo'),
  ('cybertoldo@hotmail.com','ativo','Ativo'),
  ('ddenovaisalves@gmail.com','ativo','Ativo'),
  ('djeniferscheila@hotmail.com','cancelado','Encerrou Mentoria'),
  ('elisasouzalima@yahoo.com.br','ativo','Ativo'),
  ('emimax_babii@hotmail.com','ativo','Ativo'),
  ('fernanda.c.roque@hotmail.com','ativo','Ativo'),
  ('dra_flaviamonteiro@hotmail.com','ativo','Ativo'),
  ('gabi_webers@hotmail.com','ativo','Ativo'),
  ('gisela_altoe@hotmail.com','ativo','Ativo'),
  ('driuriromanov@gmail.com','ativo','Ativo'),
  ('junnybelache@hotmail.com','ativo','Ativo'),
  ('lara_figueiredo4@hotmail.com','ativo','Ativo'),
  ('dra.larissaazevedo@gmail.com','ativo','Ativo'),
  ('layaneferreirab@gmail.com','ativo','Ativo'),
  ('leticia.b.alvim@gmail.com','ativo','Ativo'),
  ('lizardamed@hotmail.com','ativo','Ativo'),
  ('luan.tagiaroli.f@gmail.com','ativo','Ativo'),
  ('dra.luanaalegrefelix@gmail.com','ativo','Ativo'),
  ('ximenes_luciana@hotmail.com','ativo','Ativo'),
  ('marialuisagomes23@hotmail.com','ativo','Ativo'),
  ('dramariamviviane@gmail.com','ativo','Ativo'),
  ('cmateusr@gmail.com','ativo','Ativo'),
  ('mahteusferrari@gmail.com','ativo','Ativo'),
  ('naiara_fumagalli@yahoo.com.br','ativo','Ativo'),
  ('nadhinecalheiros@outlook.com','ativo','Ativo'),
  ('osnjunior@hotmail.com','ativo','Ativo'),
  ('rbmadruga@gmail.com','ativo','Ativo'),
  ('rodrigoljalves@gmail.com','ativo','Ativo'),
  ('drsandrapersonal@gmail.com','ativo','Ativo'),
  ('sszanindra@gmail.com','ativo','Ativo'),
  ('tamiris.giacomin@gmail.com','ativo','Ativo'),
  ('tatianefernandesv@gmail.com','ativo','Ativo'),
  ('taynasantiago7618@gmail.com','ativo','Ativo'),
  ('drathaiscassaroadm@gmail.com','ativo','Ativo'),
  ('drathaismendess@gmail.com','ativo','Ativo'),
  ('vaneska37@gmail.com','cancelado','Encerrou Mentoria'),
  ('vcorreamed97@gmail.com','ativo','Ativo'),
  ('vitoorkern@gmail.com','cancelado','Encerrou Mentoria'),
  ('yaratrigo@hotmail.com','ativo','Ativo'),
  ('aguinaldojsfilho@gmail.com','ativo','Ativo'),
  ('alo_jere@hotmail.com','ativo','Ativo'),
  ('amandanercolini@gmail.com','ativo','Ativo'),
  ('amandamed10@gmail.com','ativo','Ativo'),
  ('dra.ana.flavia@hotmail.com','ativo','Ativo'),
  ('analianaarrais@gmail.com','ativo','Ativo'),
  ('algaviao@hotmail.com','ativo','Ativo'),
  ('andrezadinizbh@hotmail.com','ativo','Ativo'),
  ('dra.bibianamisumi@gmail.com','ativo','Ativo'),
  ('brunosouzafaria94@gmail.com','ativo','Ativo'),
  ('caiocordeiro14@hotmail.com','ativo','Ativo'),
  ('camilaaraujooliveira@yahoo.com.br','ativo','Ativo'),
  ('camilazattaa@gmail.com','ativo','Ativo'),
  ('dailorenago@gmail.com','ativo','Ativo'),
  ('dtlopes@gmail.com','ativo','Ativo'),
  ('esteladalben@gmail.com','ativo','Ativo'),
  ('fernanda_palhares@yahoo.com.br','ativo','Ativo'),
  ('flavinhahcsi@hotmail.com','ativo','Ativo'),
  ('gabriel_comerio@hotmail.com','ativo','Ativo'),
  ('geniapithon@outlook.com','ativo','Ativo'),
  ('ginandasanchez@gmail.com','ativo','Ativo'),
  ('giselemotta@uol.com.br','ativo','Ativo'),
  ('munhoz.iga88@gmail.com','ativo','Ativo'),
  ('italo.gmv@gmail.com','ativo','Ativo'),
  ('nunesjoselia@gmail.com','ativo','Ativo'),
  ('dra.julianameyer@gmail.com','ativo','Ativo'),
  ('juliocesardelucafilho@gmail.com','ativo','Ativo'),
  ('karennrocha@hotmail.com','ativo','Ativo'),
  ('karinamoniquea@hotmail.com','ativo','Ativo'),
  ('papst.lari@gmail.com','ativo','Ativo'),
  ('layllabreve@gmail.com','ativo','Ativo'),
  ('liviaescobar16@gmail.com','ativo','Ativo'),
  ('luana_limalima@outlook.com','ativo','Ativo'),
  ('luannagvleitec@gmail.com','ativo','Ativo'),
  ('drlucas_a_campagnaro@gmail.com','ativo','Ativo'),
  ('drlucasma1994@gmail.com','ativo','Ativo'),
  ('ludi.med@gmail.com','ativo','Ativo'),
  ('dra.luisevila@gmail.com','ativo','Ativo'),
  ('drcaetano7@yahoo.com.br','ativo','Ativo'),
  ('ggertrudesouriquesteles@gmail.com','ativo','Ativo'),
  ('mariaisabel.consultorio@gmail.com','ativo','Ativo'),
  ('jutaio@hotmail.com','ativo','Ativo'),
  ('paolalmuniz@hotmail.com','ativo','Ativo'),
  ('drapatriciarezende@gmail.com','ativo','Ativo'),
  ('piaranas@gmail.com','ativo','Ativo'),
  ('rafaelly.rd@gmail.com','ativo','Ativo'),
  ('silviaval13@gmail.com','ativo','Ativo'),
  ('drasinaracastro@yahoo.com.br','ativo','Ativo'),
  ('drasofiagpereira@gmail.com','ativo','Ativo'),
  ('soniagasparoni.endocrino@gmail.com','ativo','Ativo'),
  ('tati_lauria@hotmail.com','ativo','Ativo'),
  ('thaniacunha@yahoo.com.br','ativo','Ativo'),
  ('tuannycanedo@gmail.com','ativo','Ativo'),
  ('victorsilva43@gmail.com','ativo','Ativo'),
  ('vilsonlm@hotmail.com','ativo','Ativo'),
  ('walterpitman@gmail.com','ativo','Ativo'),
  ('drawanessastival@gmail.com','ativo','Ativo'),
  ('gomeswilton50@yahoo.com','ativo','Ativo'),
  ('poliandrade15@hotmail.com','ativo','Ativo'),
  ('aliciacimada@gmail.com','ativo','Ativo'),
  ('mari.gregolini@gmail.com','ativo','Ativo'),
  ('riosnaor@gmail.com','ativo','Ativo'),
  ('begwicks@uol.com.br','ativo','Ativo'),
  ('thaysec@gmail.com','ativo','Ativo'),
  ('amisbele@gmail.com','ativo','Ativo'),
  ('drbogos61@hotmail.com','ativo','Ativo'),
  ('financeiro@nucleofw.com','ativo','Ativo'),
  ('mayveloza@hotmail.com','ativo','Ativo'),
  ('barbaracastromuniz@gmail.com','ativo','Ativo'),
  ('eduardoalencar_duda@hotmail.com','ativo','Ativo'),
  ('danielamra@hotmail.com','ativo','Ativo'),
  ('consultorioafra@gmail.com','ativo','Ativo'),
  ('gardcenci@gmail.com','ativo','Ativo'),
  ('clinicabogossian@hotmaill.com','ativo','Ativo'),
  ('ferrazfc@hotmail.com','ativo','Ativo'),
  ('drbrunopeixoto1@gmail.com','ativo','Ativo'),
  ('anaramirez@terra.com.br','ativo','Ativo'),
  ('carmenaraujolima@hotmail.com','ativo','Ativo'),
  ('alhender.bridi@hotmail.com','ativo','Ativo'),
  ('amanda_bissoli@hotmail.com','ativo','Ativo'),
  ('tinabatalha8@gmail.com','ativo','Ativo'),
  ('andreatanuri@gmail.com','ativo','Ativo'),
  ('doutorabrunasantos@hotmail.com','ativo','Ativo'),
  ('caioatps@hotmail.com','ativo','Ativo'),
  ('camilagiannecchini@gmail.com','ativo','Ativo'),
  ('contato@dracathycoelho.com','ativo','Ativo'),
  ('crismac19@yahoo.com.br','ativo','Ativo'),
  ('cbreval79@gmail.com','ativo','Ativo'),
  ('clinicamater@hotmail.com','ativo','Ativo'),
  ('divinomed@hotmail.com','ativo','Ativo'),
  ('dredgarsarmento@gmail.com','ativo','Ativo'),
  ('soccoljr@hotmail.com','ativo','Ativo'),
  ('eduardopachu350@hotmail.com','ativo','Ativo'),
  ('erikadfj@gmail.com','ativo','Ativo'),
  ('draesthela@sideclinic.com.br','ativo','Ativo'),
  ('fbalem@hotmail.com','ativo','Ativo'),
  ('fernandabrunomacedo@gmail.com','ativo','Ativo'),
  ('drafernadasd@gmail.com','ativo','Ativo'),
  ('gabrielmattos@msn.com','ativo','Ativo'),
  ('drageciele@gmail.com','ativo','Ativo'),
  ('giselle_rm@hotmail.com','ativo','Ativo'),
  ('hperesrocha@gmail.com','ativo','Ativo'),
  ('higorcaldato@outlook.com','ativo','Ativo'),
  ('drahilloa@gmail.com','ativo','Ativo'),
  ('gestaodrjoaolauro@gmail.com','ativo','Ativo'),
  ('pereirajordana94@gmail.com','ativo','Ativo'),
  ('drajuliana@gmail.com','ativo','Ativo'),
  ('katianaturon@hotmail.com','ativo','Ativo'),
  ('kelso@kelsopassos.com.br','ativo','Ativo'),
  ('lecianaramos@hotmail.com','ativo','Ativo'),
  ('livinhaninno@gmail.com','ativo','Ativo'),
  ('drlucasmirandabessa@gmail.com','ativo','Ativo'),
  ('lucio@grapeclinic.com.br','ativo','Ativo'),
  ('luisafernasopolis@hotmaik.com','ativo','Ativo'),
  ('drluissguedes@gmail.com','ativo','Ativo'),
  ('luizdcrf@gmail.com','ativo','Ativo'),
  ('marcela@grapeclinic.com.br','ativo','Ativo'),
  ('marciagineco@gmail.com','ativo','Ativo'),
  ('marcosvinicius@hotmail.com','ativo','Ativo'),
  ('mcrosenbaum@outlook.com','ativo','Ativo'),
  ('malemosps@gmail.com','ativo','Ativo'),
  ('maryvalves@hotmail.com','ativo','Ativo'),
  ('marielalmuniz@yahoo.com.br','ativo','Ativo'),
  ('marinamtbarboza@gmail.com','ativo','Ativo'),
  ('drlemosmatheus@gmail.com','ativo','Ativo'),
  ('mayaralanucy@hotmail.com','ativo','Ativo'),
  ('melvivi5@gmail.com','ativo','Ativo'),
  ('merencianaduarte@gmail.com','ativo','Ativo'),
  ('michelle.phe27@yahoo.com.br','ativo','Ativo'),
  ('nathidalpra@hotmail.com','ativo','Ativo'),
  ('drapatriciacavalcante@yahoo.com.br','ativo','Ativo'),
  ('magierpatricia@gmail.com','ativo','Ativo'),
  ('dr.pauloabreu@hotmail.com','ativo','Ativo'),
  ('pedrohluiz27@gmail.com','ativo','Ativo'),
  ('pedrotakiuti@hotmail.com','ativo','Ativo'),
  ('drapriscilanascimento63@gmail.com','ativo','Ativo'),
  ('rebellodraregina@gmail.com','ativo','Ativo'),
  ('smachado60@yahoo.com','ativo','Ativo'),
  ('saritarods@yahoo.com.br','ativo','Ativo'),
  ('drasuzanalessaplano@gmail.com','ativo','Ativo'),
  ('talitalelis2017@gmail.com','ativo','Ativo'),
  ('thiago@drthiagocollares.com','ativo','Ativo'),
  ('thiagopereiramed@yahoo.com.br','ativo','Ativo'),
  ('twoany86@hotmail.com','ativo','Ativo'),
  ('medicinavitalis@gmail.com','ativo','Ativo'),
  ('nettoninno12@gmail.com','ativo','Ativo'),
  ('aleleby@yahoo.com.br','ativo','Ativo'),
  ('sofiaccalheiros@yahoo.com.br','ativo','Ativo'),
  ('arubiap@gmail.com','ativo','Ativo'),
  ('anec.barreto.302@gmail.com','ativo','Ativo'),
  ('drabrendamendonca@gmail.com','ativo','Ativo'),
  ('dracarlafreitas@outlook.com','ativo','Ativo'),
  ('carolmsstarling@yahoo.com.br','ativo','Ativo'),
  ('dandaratureta@gmail.com','ativo','Ativo'),
  ('drdanielteixeira@gmail.com','ativo','Ativo'),
  ('dradelmanevesnutro@gmail.com','ativo','Ativo'),
  ('ftanuri@yahoo.com.br','ativo','Ativo'),
  ('contato@clinicajulianaaliprandi.com.br','ativo','Ativo'),
  ('karinerantunes@hotmail.com','ativo','Ativo'),
  ('contato@drakatiaramos.com.br','ativo','Ativo'),
  ('kennya_1104@hotmail.com','ativo','Ativo'),
  ('tonelkezia@gmail.com','ativo','Ativo'),
  ('lanakris@hotmail.com','ativo','Ativo'),
  ('lsilvaesilva@yahoo.com.br','ativo','Ativo'),
  ('leidynx1@outlook.com','ativo','Ativo'),
  ('drleonardopozzobon@hotmail.com','ativo','Ativo'),
  ('doutoralise@gmail.com','ativo','Ativo'),
  ('draliviatrevisan@gmail.com','ativo','Ativo'),
  ('lorenafernandesmelof@gmail.com','ativo','Ativo'),
  ('fc.luaira@gmail.com','ativo','Ativo'),
  ('lucasmissiba@hotmail.com','ativo','Ativo'),
  ('ludeister@hotmail.com','ativo','Ativo'),
  ('lux.tempesta@uol.com.br','ativo','Ativo'),
  ('lfcastroneves@gmail.com','ativo','Ativo'),
  ('drluizmichels@gmail.com','ativo','Ativo'),
  ('marcelafilgueiras@gmail.com','ativo','Ativo'),
  ('masj83@hotmail.com','ativo','Ativo'),
  ('mariapaula.mourac@gmail.com','ativo','Ativo'),
  ('dr.matheusdeon@gmail.com','ativo','Ativo'),
  ('mauriciofriederich@yahoo.com.br','ativo','Ativo'),
  ('miamfurlan@gmail.com','ativo','Ativo'),
  ('mmbuzzato@gmail.com','ativo','Ativo'),
  ('natalia.fioramonte@hotmail.com','ativo','Ativo'),
  ('natani_espinosa@hotmail.com','ativo','Ativo'),
  ('pamella.alves@yahoo.com.br','ativo','Ativo'),
  ('paulaavel@gmail.com','ativo','Ativo'),
  ('paula_machadomed@hotmail.com','ativo','Ativo'),
  ('doutor.mantoan@gmail.com','ativo','Ativo'),
  ('rachelsouto@gmail.com','ativo','Ativo'),
  ('filgueirasrebeca@yahoo.com.br','ativo','Ativo'),
  ('re_fernandes66@hotmail.com','ativo','Ativo'),
  ('drarenatagabrielly@gmail.com','ativo','Ativo'),
  ('drridelson@gmail.com','ativo','Ativo'),
  ('robertamiele@hotmail.com','ativo','Ativo'),
  ('robertocesarleite15@gmail.com','ativo','Ativo'),
  ('digo_irece@gmail.com','ativo','Ativo'),
  ('romolo.guida@gmail.com','ativo','Ativo'),
  ('rosana_rassi@hotmail.com','ativo','Ativo'),
  ('drasamaralima@hotmail.com','ativo','Ativo'),
  ('sara_ulhoa@hotmail.com','ativo','Ativo'),
  ('sivalle@gmail.com','ativo','Ativo'),
  ('sinara.v.p@hotmail.com','ativo','Ativo'),
  ('tainadurans@hotmail.com','ativo','Ativo'),
  ('drataniamariacarvalho@gmail.com','ativo','Ativo'),
  ('thaipaulucci@gmail.com','ativo','Ativo'),
  ('drathalitasc@gmai','ativo','Ativo'),
  ('drverissimoendocrino@gmail.com','ativo','Ativo'),
  ('vi-sacchetto@hotmail.com','ativo','Ativo'),
  ('viviandani.bastos@gmail.com','ativo','Ativo'),
  ('viviannpecly@hotmail.com','ativo','Ativo'),
  ('drwellingtonreis@outlook.com','ativo','Ativo'),
  ('wilsonbbsampaio@hotmail.com','ativo','Ativo'),
  ('drayole.endorclinica@gmail.com','ativo','Ativo'),
  ('zelmavilasboas@gmail.com','ativo','Ativo'),
  ('rafaela.nlbc@gmail.com','ativo','Ativo'),
  ('dra.valeria@clinicavalerialeal.com.br','ativo','Ativo'),
  ('maisafukayama@hotmail.com','ativo','Ativo'),
  ('anne.karoline.ferreira@hotmail.com','ativo','Ativo'),
  ('graziellyteles@hotmail.com.br','ativo','Ativo'),
  ('camillaclc@hotmail.com','ativo','Ativo'),
  ('etianneandradec@gmail.com','ativo','Ativo'),
  ('clinicadrguilhermelobo@gmail.com','ativo','Ativo'),
  ('drajanainaborges@gmail.com','ativo','Ativo'),
  ('claudiohenriquealegrebrito@gmail.com','ativo','Ativo'),
  ('contato@drdiegosilva.com.br','ativo','Ativo'),
  ('dracamilabandeira@gmail.com','ativo','Ativo'),
  ('claudia@dracaludia.com.br','ativo','Ativo'),
  ('vanessafraifeand@gmail.com','ativo','Ativo'),
  ('simoes_florio@hotmail.com','ativo','Ativo'),
  ('carolinaborgesduarte@gmail.com','ativo','Ativo'),
  ('challsiesuzarte@gmail.com','ativo','Ativo'),
  ('dqjobst@gmail.com','ativo','Ativo'),
  ('lucineidemmaia@hotmail.com','ativo','Ativo'),
  ('nandanq.cabral@gmail.com','ativo','Ativo'),
  ('karolinetorresmed@gmail.com','ativo','Ativo'),
  ('crisnavarro83@yahoo.com.br','ativo','Ativo'),
  ('drajessicasrepolho@gmail.com','ativo','Ativo'),
  ('dramanuelamcz@gmail.com','ativo','Ativo'),
  ('gabrielbastos@yahoo.com','ativo','Ativo'),
  ('georgianagama07@gmail.com','ativo','Ativo'),
  ('andressa.brunelli@hotmail.com','ativo','Ativo'),
  ('getuliojs@gmail.com','ativo','Ativo'),
  ('arthurbarros2@gmail.com','ativo','Ativo'),
  ('ingridlima-25@hotmail.com','ativo','Ativo'),
  ('gynederme@gmail.com','ativo','Ativo'),
  ('igorbalves@gmail.com','ativo','Ativo'),
  ('drakarline@gmail.com','ativo','Ativo'),
  ('hellena.gabriella@hotmail.com','ativo','Ativo'),
  ('dr.diegofernando99@gmail.com','ativo','Ativo'),
  ('brunolandin@yahoo.com.br','ativo','Ativo'),
  ('izabelarezende10@hotmail.com','ativo','Ativo'),
  ('katrinarocha02@hotmail.com','ativo','Ativo'),
  ('fabiolapfrotamed@gmail.com','ativo','Ativo'),
  ('flavia.alves.m@hotmail.com','ativo','Ativo'),
  ('bmourasousa@yahoo.com.br','ativo','Ativo'),
  ('edaianefranco@gmail.com','ativo','Ativo'),
  ('edmo_galvao@hotmail.com','ativo','Ativo'),
  ('enfnetto@yahoo.com.br','ativo','Ativo'),
  ('carlosbronzel@hotmail.com','ativo','Ativo'),
  ('contato@dragabrielabecker.com','ativo','Ativo'),
  ('dra.anacarolinarocha@outlook.com','ativo','Ativo'),
  ('cristianepsaguiar@gmail.com','ativo','Ativo'),
  ('esteticalaseraf@gmail.com','ativo','Ativo'),
  ('bellaclin@hotmail.com','ativo','Ativo'),
  ('dra.elinesoriano@gmail.com','ativo','Ativo'),
  ('freitasjoaopaulo@hotmail.com','ativo','Ativo'),
  ('cibelepimentel.ciclinic@yahoo.com.br','ativo','Ativo'),
  ('biazillmer@hotmail.com','ativo','Ativo'),
  ('indymed@live.com','ativo','Ativo'),
  ('marcos_opa@yahoo.com.br','ativo','Ativo'),
  ('jessika_katriny@hotmail.com','ativo','Ativo'),
  ('ccybelee@hotmail.com','ativo','Ativo'),
  ('elisabetemrp@gmail.com','ativo','Ativo'),
  ('drfredcorte@hotmail.com','ativo','Ativo'),
  ('isadoramachadodeoliveira@hotmail.com','ativo','Ativo'),
  ('luannagpperea@gmail.com','ativo','Ativo'),
  ('bpfranca@yahoo.com.br','ativo','Ativo'),
  ('go.anacsiqueira@gmail.com','ativo','Ativo'),
  ('mcrconsultorio@gmail.com','ativo','Ativo'),
  ('ypcserra@gmail.com','ativo','Ativo'),
  ('dralexbarros@gmail.com','ativo','Ativo'),
  ('dra.camila@clinicacasapaes.com.br','cancelado','Encerrou Mentoria'),
  ('gabrielalaboissiere@gmail.com','cancelado','Encerrou Mentoria'),
  ('luiscngarcia@gmail.com','cancelado','Encerrou Mentoria'),
  ('dramarilia.vaz@gmail.com','cancelado','Encerrou Mentoria'),
  ('pauladscorrea@gmail.com','cancelado','Encerrou Mentoria'),
  ('rominaendocrino@gmail.com','cancelado','Encerrou Mentoria'),
  ('donatti.a.x@gmail.com','cancelado','Encerrou Mentoria'),
  ('drmichaelcaminha@gmail.com','cancelado','Encerrou Mentoria'),
  ('marcelamedufu@gmail.com','cancelado','Encerrou Mentoria'),
  ('nandalimafls@gmail.com','cancelado','Encerrou Mentoria'),
  ('gustavocaldeiradr@gmail.com','cancelado','Encerrou Mentoria'),
  ('manoelapietro91@gmail.com','ativo','Resolvendo'),
  ('dradeborahschmitt@gmail.com','ativo','Resolvendo'),
  ('fernandaabirihan@gmail.com','ativo','Resolvendo'),
  ('juliapabrahao95@gmail.com','ativo','Resolvendo'),
  ('raquelssito@hotmail.com','ativo','Resolvendo'),
  ('renataortiz3@hotmail.com','ativo','Resolvendo'),
  ('wilsonmarquesam@gmail.com','ativo','Resolvendo'),
  ('dandaralacerda@hotmail.com','ativo','Resolvendo'),
  ('fernandafernandesm@hotmail.com','ativo','Resolvendo'),
  ('amandadearruda@hotmail.com','ativo','Resolvendo'),
  ('juliananoronhapinheiro@gmail.com','ativo','Resolvendo'),
  ('lukstosi@hotmail.com','ativo','Resolvendo'),
  ('andrecasteloes@hotmail.com','trancado','Ativo'),
  ('dr.cleissonborges@gmail.com','trancado','Ativo'),
  ('danyafreitas@hotmail.com','trancado','Ativo'),
  ('joaopaulovitorino@hotmail.com','trancado','Ativo'),
  ('jonascortez@nutriterapica.com','trancado','Ativo'),
  ('kkmontenegroc@gmail.com','trancado','Ativo'),
  ('karolinalencar.med@gmail.com','trancado','Ativo'),
  ('marco.rmoraes@gmail.com','trancado','Ativo'),
  ('marinamreis@yahoo.com.br','trancado','Ativo'),
  ('frias@cardiol.br','trancado','Ativo'),
  ('ronaldoborgesmendes@gmail.com','trancado','Ativo'),
  ('drasabrinaribeironutro@gmail.com','trancado','Ativo')
on conflict (email) do nothing;

-- ---------- 1) ANTES: como está hoje ----------
select status, count(*) from students group by status order by 2 desc;

-- ---------- 2) corrige ----------
update students s
   set status = p.status_real,
       renewal_status = case when p.rotulo = 'Resolvendo' then 'Resolvendo'
                             else s.renewal_status end,
       oculto_diretoria = (p.rotulo = 'Encerrou Mentoria')
  from status_planilha p
 where lower(s.email) = p.email
   and (s.status is distinct from p.status_real
        or s.oculto_diretoria is distinct from (p.rotulo = 'Encerrou Mentoria'));

-- entrega de quem trancou/encerrou não fica 'ativo'
update deliveries d set status = 'inativo'
  from students s
 where d.student_id = s.id and s.status in ('trancado','cancelado','inativo')
   and d.status = 'ativo';

-- ---------- 3) DEPOIS: tem que bater com a planilha ----------
select status, count(*) from students group by status order by 2 desc;

select
  (select count(*) from students where status = 'ativo')      as ativos,
  (select count(*) from students where status = 'trancado')   as trancados,
  (select count(*) from students where renewal_status = 'Resolvendo') as resolvendo,
  (select count(*) from students where status = 'cancelado')  as encerraram,
  (select count(*) from students)                             as total_cadastrado;

-- ---------- 4) quem o sistema tem e a planilha NÃO ----------
-- A Thaís precisa dizer o que fazer com cada um: pode ser aluno que entrou
-- pela Cademi depois, ou cadastro velho que deveria estar inativo.
select s.full_name, s.email, s.status, s.entry_date,
       st.full_name as cs, s.created_at::date as cadastrado_em
  from students s
  left join staff st on st.id = s.cs_id
 where not exists (select 1 from status_planilha p where p.email = lower(s.email))
 order by s.created_at desc nulls last;

-- ---------- 5) SÓ DEPOIS DE CONFERIR O 4 ----------
-- Tira da contagem de ativos quem não está na planilha da Thaís.
-- Descomente as duas linhas abaixo quando ela confirmar.
-- update students s set status = 'inativo'
--  where not exists (select 1 from status_planilha p where p.email = lower(s.email));
